/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Backend | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient,
  HttpHeaders
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpParams,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  AdminLoginAsRequest,
  AdminSchematicListResponse,
  AdminToggleSchematicRequest,
  AdminUserDetailResponse,
  AdminUserListResponse,
  AllowedTagRequest,
  AllowedTagResponse,
  AllowedVersionRequest,
  AllowedVersionResponse,
  ChangeUserBadgeRequest,
  ChangeUserQuotaRequest,
  ChangeUserRoleRequest,
  ChangeUserStatusRequest,
  GetApiAdminSchematicsParams,
  GetApiAdminStorageParams,
  GetApiAdminUsersParams,
  LiveMessageRequest,
  LiveMessageResponse,
  LoginResponse,
  ModMessageRequest,
  ModMessageResponse,
  StorageStatsResponse
} from './generated.schemas';




interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
        | HttpParams
      | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: {includeHeaders?: string[]} | boolean;
}

function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: Set<string> = new Set(),
): Record<string, string | number | boolean | Array<string | number | boolean>> {
  const filteredParams: Record<string, string | number | boolean | null | Array<string | number | boolean>> = {};
  for (const [key, value] of Object.entries(params)) {
    if (Array.isArray(value)) {
      const filtered = value.filter(
        (item) =>
          item != null &&
          (typeof item === 'string' ||
            typeof item === 'number' ||
            typeof item === 'boolean'),
      ) as Array<string | number | boolean>;
      if (filtered.length) {
        filteredParams[key] = filtered;
      }
    } else if (value === null && requiredNullableKeys.has(key)) {
      filteredParams[key] = value;
    } else if (
      value != null &&
      (typeof value === 'string' ||
        typeof value === 'number' ||
        typeof value === 'boolean')
    ) {
      filteredParams[key] = value as string | number | boolean;
    }
  }
  return filteredParams as Record<string, string | number | boolean | Array<string | number | boolean>>;
}



@Injectable({ providedIn: 'root' })
export class AdminService {
  private readonly http = inject(HttpClient);
 getApiAdminUsers<TData = AdminUserListResponse>(params?: GetApiAdminUsersParams, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 getApiAdminUsers<TData = AdminUserListResponse>(params?: GetApiAdminUsersParams, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 getApiAdminUsers<TData = AdminUserListResponse>(params?: GetApiAdminUsersParams, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  getApiAdminUsers<TData = AdminUserListResponse>(
    params?: GetApiAdminUsersParams, options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    const filteredParams = filterParams({...params, ...options?.params}, new Set<string>([]));

    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/Admin/users`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
        params: filteredParams,}
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/Admin/users`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
        params: filteredParams,}
    );
    }

    return this.http.get<TData>(
      `/api/Admin/users`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
        params: filteredParams,}
    );
  }
 getApiAdminUsersId<TData = AdminUserDetailResponse>(id: string, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 getApiAdminUsersId<TData = AdminUserDetailResponse>(id: string, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 getApiAdminUsersId<TData = AdminUserDetailResponse>(id: string, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  getApiAdminUsersId<TData = AdminUserDetailResponse>(
    id: string, options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/Admin/users/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/Admin/users/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/Admin/users/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 postApiAdminUsersIdStatus<TData = unknown>(id: string,
    changeUserStatusRequest: ChangeUserStatusRequest, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiAdminUsersIdStatus<TData = unknown>(id: string,
    changeUserStatusRequest: ChangeUserStatusRequest, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiAdminUsersIdStatus<TData = unknown>(id: string,
    changeUserStatusRequest: ChangeUserStatusRequest, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiAdminUsersIdStatus<TData = unknown>(
    id: string,
    changeUserStatusRequest: ChangeUserStatusRequest, options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/Admin/users/${id}/status`,
      changeUserStatusRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/Admin/users/${id}/status`,
      changeUserStatusRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/Admin/users/${id}/status`,
      changeUserStatusRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 postApiAdminUsersIdRole<TData = unknown>(id: string,
    changeUserRoleRequest: ChangeUserRoleRequest, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiAdminUsersIdRole<TData = unknown>(id: string,
    changeUserRoleRequest: ChangeUserRoleRequest, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiAdminUsersIdRole<TData = unknown>(id: string,
    changeUserRoleRequest: ChangeUserRoleRequest, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiAdminUsersIdRole<TData = unknown>(
    id: string,
    changeUserRoleRequest: ChangeUserRoleRequest, options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/Admin/users/${id}/role`,
      changeUserRoleRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/Admin/users/${id}/role`,
      changeUserRoleRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/Admin/users/${id}/role`,
      changeUserRoleRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 postApiAdminUsersIdBadge<TData = unknown>(id: string,
    changeUserBadgeRequest: ChangeUserBadgeRequest, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiAdminUsersIdBadge<TData = unknown>(id: string,
    changeUserBadgeRequest: ChangeUserBadgeRequest, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiAdminUsersIdBadge<TData = unknown>(id: string,
    changeUserBadgeRequest: ChangeUserBadgeRequest, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiAdminUsersIdBadge<TData = unknown>(
    id: string,
    changeUserBadgeRequest: ChangeUserBadgeRequest, options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/Admin/users/${id}/badge`,
      changeUserBadgeRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/Admin/users/${id}/badge`,
      changeUserBadgeRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/Admin/users/${id}/badge`,
      changeUserBadgeRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 postApiAdminUsersIdQuota<TData = unknown>(id: string,
    changeUserQuotaRequest: ChangeUserQuotaRequest, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiAdminUsersIdQuota<TData = unknown>(id: string,
    changeUserQuotaRequest: ChangeUserQuotaRequest, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiAdminUsersIdQuota<TData = unknown>(id: string,
    changeUserQuotaRequest: ChangeUserQuotaRequest, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiAdminUsersIdQuota<TData = unknown>(
    id: string,
    changeUserQuotaRequest: ChangeUserQuotaRequest, options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/Admin/users/${id}/quota`,
      changeUserQuotaRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/Admin/users/${id}/quota`,
      changeUserQuotaRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/Admin/users/${id}/quota`,
      changeUserQuotaRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 deleteApiAdminUsersIdApiKey<TData = unknown>(id: string, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 deleteApiAdminUsersIdApiKey<TData = unknown>(id: string, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 deleteApiAdminUsersIdApiKey<TData = unknown>(id: string, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  deleteApiAdminUsersIdApiKey<TData = unknown>(
    id: string, options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.delete<TData>(
      `/api/Admin/users/${id}/api-key`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.delete<TData>(
      `/api/Admin/users/${id}/api-key`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.delete<TData>(
      `/api/Admin/users/${id}/api-key`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 deleteApiAdminUsersIdSaveKey<TData = unknown>(id: string, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 deleteApiAdminUsersIdSaveKey<TData = unknown>(id: string, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 deleteApiAdminUsersIdSaveKey<TData = unknown>(id: string, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  deleteApiAdminUsersIdSaveKey<TData = unknown>(
    id: string, options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.delete<TData>(
      `/api/Admin/users/${id}/save-key`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.delete<TData>(
      `/api/Admin/users/${id}/save-key`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.delete<TData>(
      `/api/Admin/users/${id}/save-key`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 postApiAdminUsersLoginAs<TData = LoginResponse>(adminLoginAsRequest: AdminLoginAsRequest, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiAdminUsersLoginAs<TData = LoginResponse>(adminLoginAsRequest: AdminLoginAsRequest, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiAdminUsersLoginAs<TData = LoginResponse>(adminLoginAsRequest: AdminLoginAsRequest, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiAdminUsersLoginAs<TData = LoginResponse>(
    adminLoginAsRequest: AdminLoginAsRequest, options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/Admin/users/login-as`,
      adminLoginAsRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/Admin/users/login-as`,
      adminLoginAsRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/Admin/users/login-as`,
      adminLoginAsRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 postApiAdminUsersIdResetReports<TData = unknown>(id: string, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiAdminUsersIdResetReports<TData = unknown>(id: string, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiAdminUsersIdResetReports<TData = unknown>(id: string, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiAdminUsersIdResetReports<TData = unknown>(
    id: string, options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/Admin/users/${id}/reset-reports`,undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/Admin/users/${id}/reset-reports`,undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/Admin/users/${id}/reset-reports`,undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 getApiAdminSchematics<TData = AdminSchematicListResponse>(params?: GetApiAdminSchematicsParams, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 getApiAdminSchematics<TData = AdminSchematicListResponse>(params?: GetApiAdminSchematicsParams, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 getApiAdminSchematics<TData = AdminSchematicListResponse>(params?: GetApiAdminSchematicsParams, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  getApiAdminSchematics<TData = AdminSchematicListResponse>(
    params?: GetApiAdminSchematicsParams, options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    const filteredParams = filterParams({...params, ...options?.params}, new Set<string>([]));

    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/Admin/schematics`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
        params: filteredParams,}
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/Admin/schematics`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
        params: filteredParams,}
    );
    }

    return this.http.get<TData>(
      `/api/Admin/schematics`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
        params: filteredParams,}
    );
  }
 postApiAdminSchematicsIdToggle<TData = unknown>(id: string,
    adminToggleSchematicRequest: AdminToggleSchematicRequest, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiAdminSchematicsIdToggle<TData = unknown>(id: string,
    adminToggleSchematicRequest: AdminToggleSchematicRequest, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiAdminSchematicsIdToggle<TData = unknown>(id: string,
    adminToggleSchematicRequest: AdminToggleSchematicRequest, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiAdminSchematicsIdToggle<TData = unknown>(
    id: string,
    adminToggleSchematicRequest: AdminToggleSchematicRequest, options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/Admin/schematics/${id}/toggle`,
      adminToggleSchematicRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/Admin/schematics/${id}/toggle`,
      adminToggleSchematicRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/Admin/schematics/${id}/toggle`,
      adminToggleSchematicRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 postApiAdminSchematicsIdResetReports<TData = unknown>(id: string, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiAdminSchematicsIdResetReports<TData = unknown>(id: string, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiAdminSchematicsIdResetReports<TData = unknown>(id: string, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiAdminSchematicsIdResetReports<TData = unknown>(
    id: string, options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/Admin/schematics/${id}/reset-reports`,undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/Admin/schematics/${id}/reset-reports`,undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/Admin/schematics/${id}/reset-reports`,undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 getApiAdminLiveMessages<TData = LiveMessageResponse[]>( options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 getApiAdminLiveMessages<TData = LiveMessageResponse[]>( options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 getApiAdminLiveMessages<TData = LiveMessageResponse[]>( options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  getApiAdminLiveMessages<TData = LiveMessageResponse[]>(
     options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/Admin/live-messages`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/Admin/live-messages`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/Admin/live-messages`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 postApiAdminLiveMessages<TData = LiveMessageResponse>(liveMessageRequest: LiveMessageRequest, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiAdminLiveMessages<TData = LiveMessageResponse>(liveMessageRequest: LiveMessageRequest, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiAdminLiveMessages<TData = LiveMessageResponse>(liveMessageRequest: LiveMessageRequest, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiAdminLiveMessages<TData = LiveMessageResponse>(
    liveMessageRequest: LiveMessageRequest, options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/Admin/live-messages`,
      liveMessageRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/Admin/live-messages`,
      liveMessageRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/Admin/live-messages`,
      liveMessageRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 putApiAdminLiveMessagesId<TData = LiveMessageResponse>(id: number,
    liveMessageRequest: LiveMessageRequest, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 putApiAdminLiveMessagesId<TData = LiveMessageResponse>(id: number,
    liveMessageRequest: LiveMessageRequest, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 putApiAdminLiveMessagesId<TData = LiveMessageResponse>(id: number,
    liveMessageRequest: LiveMessageRequest, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  putApiAdminLiveMessagesId<TData = LiveMessageResponse>(
    id: number,
    liveMessageRequest: LiveMessageRequest, options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.put<TData>(
      `/api/Admin/live-messages/${id}`,
      liveMessageRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.put<TData>(
      `/api/Admin/live-messages/${id}`,
      liveMessageRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.put<TData>(
      `/api/Admin/live-messages/${id}`,
      liveMessageRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 deleteApiAdminLiveMessagesId<TData = unknown>(id: number, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 deleteApiAdminLiveMessagesId<TData = unknown>(id: number, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 deleteApiAdminLiveMessagesId<TData = unknown>(id: number, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  deleteApiAdminLiveMessagesId<TData = unknown>(
    id: number, options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.delete<TData>(
      `/api/Admin/live-messages/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.delete<TData>(
      `/api/Admin/live-messages/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.delete<TData>(
      `/api/Admin/live-messages/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 getApiAdminModMessages<TData = ModMessageResponse[]>( options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 getApiAdminModMessages<TData = ModMessageResponse[]>( options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 getApiAdminModMessages<TData = ModMessageResponse[]>( options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  getApiAdminModMessages<TData = ModMessageResponse[]>(
     options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/Admin/mod-messages`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/Admin/mod-messages`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/Admin/mod-messages`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 postApiAdminModMessages<TData = ModMessageResponse>(modMessageRequest: ModMessageRequest, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiAdminModMessages<TData = ModMessageResponse>(modMessageRequest: ModMessageRequest, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiAdminModMessages<TData = ModMessageResponse>(modMessageRequest: ModMessageRequest, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiAdminModMessages<TData = ModMessageResponse>(
    modMessageRequest: ModMessageRequest, options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/Admin/mod-messages`,
      modMessageRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/Admin/mod-messages`,
      modMessageRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/Admin/mod-messages`,
      modMessageRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 postApiAdminModMessagesIdToggle<TData = unknown>(id: number, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiAdminModMessagesIdToggle<TData = unknown>(id: number, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiAdminModMessagesIdToggle<TData = unknown>(id: number, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiAdminModMessagesIdToggle<TData = unknown>(
    id: number, options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/Admin/mod-messages/${id}/toggle`,undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/Admin/mod-messages/${id}/toggle`,undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/Admin/mod-messages/${id}/toggle`,undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 deleteApiAdminModMessagesId<TData = unknown>(id: number, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 deleteApiAdminModMessagesId<TData = unknown>(id: number, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 deleteApiAdminModMessagesId<TData = unknown>(id: number, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  deleteApiAdminModMessagesId<TData = unknown>(
    id: number, options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.delete<TData>(
      `/api/Admin/mod-messages/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.delete<TData>(
      `/api/Admin/mod-messages/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.delete<TData>(
      `/api/Admin/mod-messages/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 getApiAdminStorage<TData = StorageStatsResponse>(params?: GetApiAdminStorageParams, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 getApiAdminStorage<TData = StorageStatsResponse>(params?: GetApiAdminStorageParams, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 getApiAdminStorage<TData = StorageStatsResponse>(params?: GetApiAdminStorageParams, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  getApiAdminStorage<TData = StorageStatsResponse>(
    params?: GetApiAdminStorageParams, options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    const filteredParams = filterParams({...params, ...options?.params}, new Set<string>([]));

    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/Admin/storage`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
        params: filteredParams,}
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/Admin/storage`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
        params: filteredParams,}
    );
    }

    return this.http.get<TData>(
      `/api/Admin/storage`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
        params: filteredParams,}
    );
  }
 getApiAdminTags<TData = AllowedTagResponse[]>( options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 getApiAdminTags<TData = AllowedTagResponse[]>( options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 getApiAdminTags<TData = AllowedTagResponse[]>( options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  getApiAdminTags<TData = AllowedTagResponse[]>(
     options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/Admin/tags`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/Admin/tags`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/Admin/tags`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 postApiAdminTags<TData = AllowedTagResponse>(allowedTagRequest: AllowedTagRequest, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiAdminTags<TData = AllowedTagResponse>(allowedTagRequest: AllowedTagRequest, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiAdminTags<TData = AllowedTagResponse>(allowedTagRequest: AllowedTagRequest, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiAdminTags<TData = AllowedTagResponse>(
    allowedTagRequest: AllowedTagRequest, options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/Admin/tags`,
      allowedTagRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/Admin/tags`,
      allowedTagRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/Admin/tags`,
      allowedTagRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 deleteApiAdminTagsId<TData = unknown>(id: number, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 deleteApiAdminTagsId<TData = unknown>(id: number, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 deleteApiAdminTagsId<TData = unknown>(id: number, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  deleteApiAdminTagsId<TData = unknown>(
    id: number, options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.delete<TData>(
      `/api/Admin/tags/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.delete<TData>(
      `/api/Admin/tags/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.delete<TData>(
      `/api/Admin/tags/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 getApiAdminVersions<TData = AllowedVersionResponse[]>( options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 getApiAdminVersions<TData = AllowedVersionResponse[]>( options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 getApiAdminVersions<TData = AllowedVersionResponse[]>( options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  getApiAdminVersions<TData = AllowedVersionResponse[]>(
     options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/Admin/versions`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/Admin/versions`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/Admin/versions`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 postApiAdminVersions<TData = AllowedVersionResponse>(allowedVersionRequest: AllowedVersionRequest, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiAdminVersions<TData = AllowedVersionResponse>(allowedVersionRequest: AllowedVersionRequest, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiAdminVersions<TData = AllowedVersionResponse>(allowedVersionRequest: AllowedVersionRequest, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiAdminVersions<TData = AllowedVersionResponse>(
    allowedVersionRequest: AllowedVersionRequest, options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/Admin/versions`,
      allowedVersionRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/Admin/versions`,
      allowedVersionRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/Admin/versions`,
      allowedVersionRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 deleteApiAdminVersionsId<TData = unknown>(id: number, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 deleteApiAdminVersionsId<TData = unknown>(id: number, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 deleteApiAdminVersionsId<TData = unknown>(id: number, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  deleteApiAdminVersionsId<TData = unknown>(
    id: number, options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.delete<TData>(
      `/api/Admin/versions/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.delete<TData>(
      `/api/Admin/versions/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.delete<TData>(
      `/api/Admin/versions/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
}

