/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Backend | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient,
  HttpHeaders,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpParams
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  AcceptTagSuggestionRequest,
  AdminLoginAsRequest,
  AdminModuleListResponse,
  AdminModuleResponse,
  AdminModuleUpdateRequest,
  AdminNotificationResponse,
  AdminSchematicListResponse,
  AdminToggleSchematicRequest,
  AdminUserDetailResponse,
  AdminUserListResponse,
  AllowedTagRequest,
  AllowedTagResponse,
  AllowedVersionRequest,
  AllowedVersionResponse,
  ChangeUserBadgeRequest,
  ChangeUserNoteRequest,
  ChangeUserQuotaRequest,
  ChangeUserRoleRequest,
  ChangeUserStatusRequest,
  ContactTicketResponse,
  FaqCreateRequest,
  FaqResponse,
  FaqUpdateRequest,
  TicketReplyRequest,
  GetApiAdminModulesParams,
  GetApiAdminSchematicsParams,
  GetApiAdminServerLogsParams,
  GetApiAdminStorageParams,
  GetApiAdminTicketsParams,
  GetApiAdminUsersParams,
  LiveMessageRequest,
  LiveMessageResponse,
  LoginResponse,
  ModMessageRequest,
  ModMessageResponse,
  PostApiAdminModulesBody,
  StorageStatsResponse,
  TagSuggestionResponse
} from './generated.schemas';




interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
        | HttpParams
      | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: {includeHeaders?: string[]} | boolean;
  readonly timeout?: number;
}

type HttpClientBodyOptions = HttpClientOptions & {
  readonly observe?: 'body';
};

type HttpClientEventOptions = HttpClientOptions & {
  readonly observe: 'events';
};

type HttpClientResponseOptions = HttpClientOptions & {
  readonly observe: 'response';
};

type HttpClientObserveOptions = HttpClientOptions & {
  readonly observe?: 'body' | 'events' | 'response';
};

type AngularHttpParamValue = string | number | boolean | Array<string | number | boolean>;
type AngularHttpParamValueWithNullable = AngularHttpParamValue | null;

function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys?: ReadonlySet<string>,
  preserveRequiredNullables?: false,
  passthroughKeys?: undefined,
): Record<string, AngularHttpParamValue>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> | undefined,
  preserveRequiredNullables: true,
  passthroughKeys?: undefined,
): Record<string, AngularHttpParamValueWithNullable>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> | undefined,
  preserveRequiredNullables: boolean | undefined,
  passthroughKeys: ReadonlySet<string>,
): Record<string, unknown>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> = new Set(),
  preserveRequiredNullables = false,
  passthroughKeys: ReadonlySet<string> = new Set(),
): Record<string, unknown> {
  const filteredParams: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(params)) {
    if (passthroughKeys.has(key)) {
      if (value !== undefined) {
        filteredParams[key] = value;
      }
      continue;
    }
    if (Array.isArray(value)) {
      const filtered = value.filter(
        (item) =>
          item != null &&
          (typeof item === 'string' ||
            typeof item === 'number' ||
            typeof item === 'boolean'),
      ) as Array<string | number | boolean>;
      if (filtered.length) {
        filteredParams[key] = filtered;
      }
    } else if (
      preserveRequiredNullables &&
      value === null &&
      requiredNullableKeys.has(key)
    ) {
      filteredParams[key] = null;
    } else if (
      value != null &&
      (typeof value === 'string' ||
        typeof value === 'number' ||
        typeof value === 'boolean')
    ) {
      filteredParams[key] = value;
    }
  }
  return filteredParams;
}





@Injectable({ providedIn: 'root' })
export class AdminService {
  private readonly http = inject(HttpClient);
 getApiAdminUsers<TData = AdminUserListResponse>(params?: GetApiAdminUsersParams, options?: HttpClientBodyOptions): Observable<TData>;
 getApiAdminUsers<TData = AdminUserListResponse>(params?: GetApiAdminUsersParams, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getApiAdminUsers<TData = AdminUserListResponse>(params?: GetApiAdminUsersParams, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getApiAdminUsers<TData = AdminUserListResponse>(
    params?: GetApiAdminUsersParams, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    const filteredParams = filterParams({...params, ...options?.params}, new Set<string>([]));

    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/Admin/users`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
        params: filteredParams,}
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/Admin/users`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
        params: filteredParams,}
    );
    }

    return this.http.get<TData>(
      `/api/Admin/users`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
        params: filteredParams,}
    );
  }
 getApiAdminUsersId<TData = AdminUserDetailResponse>(id: string, options?: HttpClientBodyOptions): Observable<TData>;
 getApiAdminUsersId<TData = AdminUserDetailResponse>(id: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getApiAdminUsersId<TData = AdminUserDetailResponse>(id: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getApiAdminUsersId<TData = AdminUserDetailResponse>(
    id: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/Admin/users/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/Admin/users/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/Admin/users/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 postApiAdminUsersIdStatus<TData = unknown>(id: string,
    changeUserStatusRequest: ChangeUserStatusRequest, options?: HttpClientBodyOptions): Observable<TData>;
 postApiAdminUsersIdStatus<TData = unknown>(id: string,
    changeUserStatusRequest: ChangeUserStatusRequest, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiAdminUsersIdStatus<TData = unknown>(id: string,
    changeUserStatusRequest: ChangeUserStatusRequest, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiAdminUsersIdStatus<TData = unknown>(
    id: string,
    changeUserStatusRequest: ChangeUserStatusRequest, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/Admin/users/${id}/status`,
      changeUserStatusRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/Admin/users/${id}/status`,
      changeUserStatusRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/Admin/users/${id}/status`,
      changeUserStatusRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 postApiAdminUsersIdRole<TData = unknown>(id: string,
    changeUserRoleRequest: ChangeUserRoleRequest, options?: HttpClientBodyOptions): Observable<TData>;
 postApiAdminUsersIdRole<TData = unknown>(id: string,
    changeUserRoleRequest: ChangeUserRoleRequest, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiAdminUsersIdRole<TData = unknown>(id: string,
    changeUserRoleRequest: ChangeUserRoleRequest, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiAdminUsersIdRole<TData = unknown>(
    id: string,
    changeUserRoleRequest: ChangeUserRoleRequest, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/Admin/users/${id}/role`,
      changeUserRoleRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/Admin/users/${id}/role`,
      changeUserRoleRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/Admin/users/${id}/role`,
      changeUserRoleRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 postApiAdminUsersIdBadge<TData = unknown>(id: string,
    changeUserBadgeRequest: ChangeUserBadgeRequest, options?: HttpClientBodyOptions): Observable<TData>;
 postApiAdminUsersIdBadge<TData = unknown>(id: string,
    changeUserBadgeRequest: ChangeUserBadgeRequest, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiAdminUsersIdBadge<TData = unknown>(id: string,
    changeUserBadgeRequest: ChangeUserBadgeRequest, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiAdminUsersIdBadge<TData = unknown>(
    id: string,
    changeUserBadgeRequest: ChangeUserBadgeRequest, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/Admin/users/${id}/badge`,
      changeUserBadgeRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/Admin/users/${id}/badge`,
      changeUserBadgeRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/Admin/users/${id}/badge`,
      changeUserBadgeRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 postApiAdminUsersIdQuota<TData = unknown>(id: string,
    changeUserQuotaRequest: ChangeUserQuotaRequest, options?: HttpClientBodyOptions): Observable<TData>;
 postApiAdminUsersIdQuota<TData = unknown>(id: string,
    changeUserQuotaRequest: ChangeUserQuotaRequest, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiAdminUsersIdQuota<TData = unknown>(id: string,
    changeUserQuotaRequest: ChangeUserQuotaRequest, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiAdminUsersIdQuota<TData = unknown>(
    id: string,
    changeUserQuotaRequest: ChangeUserQuotaRequest, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/Admin/users/${id}/quota`,
      changeUserQuotaRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/Admin/users/${id}/quota`,
      changeUserQuotaRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/Admin/users/${id}/quota`,
      changeUserQuotaRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 postApiAdminUsersIdNote<TData = unknown>(id: string,
    changeUserNoteRequest: ChangeUserNoteRequest, options?: HttpClientBodyOptions): Observable<TData>;
 postApiAdminUsersIdNote<TData = unknown>(id: string,
    changeUserNoteRequest: ChangeUserNoteRequest, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiAdminUsersIdNote<TData = unknown>(id: string,
    changeUserNoteRequest: ChangeUserNoteRequest, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiAdminUsersIdNote<TData = unknown>(
    id: string,
    changeUserNoteRequest: ChangeUserNoteRequest, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/Admin/users/${id}/note`,
      changeUserNoteRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/Admin/users/${id}/note`,
      changeUserNoteRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/Admin/users/${id}/note`,
      changeUserNoteRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 deleteApiAdminUsersIdApiKey<TData = unknown>(id: string, options?: HttpClientBodyOptions): Observable<TData>;
 deleteApiAdminUsersIdApiKey<TData = unknown>(id: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 deleteApiAdminUsersIdApiKey<TData = unknown>(id: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  deleteApiAdminUsersIdApiKey<TData = unknown>(
    id: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.delete<TData>(
      `/api/Admin/users/${id}/api-key`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.delete<TData>(
      `/api/Admin/users/${id}/api-key`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.delete<TData>(
      `/api/Admin/users/${id}/api-key`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 deleteApiAdminUsersIdSaveKey<TData = unknown>(id: string, options?: HttpClientBodyOptions): Observable<TData>;
 deleteApiAdminUsersIdSaveKey<TData = unknown>(id: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 deleteApiAdminUsersIdSaveKey<TData = unknown>(id: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  deleteApiAdminUsersIdSaveKey<TData = unknown>(
    id: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.delete<TData>(
      `/api/Admin/users/${id}/save-key`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.delete<TData>(
      `/api/Admin/users/${id}/save-key`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.delete<TData>(
      `/api/Admin/users/${id}/save-key`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 postApiAdminUsersLoginAs<TData = LoginResponse>(adminLoginAsRequest: AdminLoginAsRequest, options?: HttpClientBodyOptions): Observable<TData>;
 postApiAdminUsersLoginAs<TData = LoginResponse>(adminLoginAsRequest: AdminLoginAsRequest, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiAdminUsersLoginAs<TData = LoginResponse>(adminLoginAsRequest: AdminLoginAsRequest, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiAdminUsersLoginAs<TData = LoginResponse>(
    adminLoginAsRequest: AdminLoginAsRequest, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/Admin/users/login-as`,
      adminLoginAsRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/Admin/users/login-as`,
      adminLoginAsRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/Admin/users/login-as`,
      adminLoginAsRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 postApiAdminUsersIdResetReports<TData = unknown>(id: string, options?: HttpClientBodyOptions): Observable<TData>;
 postApiAdminUsersIdResetReports<TData = unknown>(id: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiAdminUsersIdResetReports<TData = unknown>(id: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiAdminUsersIdResetReports<TData = unknown>(
    id: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/Admin/users/${id}/reset-reports`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/Admin/users/${id}/reset-reports`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/Admin/users/${id}/reset-reports`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 getApiAdminSchematics<TData = AdminSchematicListResponse>(params?: GetApiAdminSchematicsParams, options?: HttpClientBodyOptions): Observable<TData>;
 getApiAdminSchematics<TData = AdminSchematicListResponse>(params?: GetApiAdminSchematicsParams, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getApiAdminSchematics<TData = AdminSchematicListResponse>(params?: GetApiAdminSchematicsParams, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getApiAdminSchematics<TData = AdminSchematicListResponse>(
    params?: GetApiAdminSchematicsParams, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    const filteredParams = filterParams({...params, ...options?.params}, new Set<string>([]));

    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/Admin/schematics`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
        params: filteredParams,}
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/Admin/schematics`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
        params: filteredParams,}
    );
    }

    return this.http.get<TData>(
      `/api/Admin/schematics`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
        params: filteredParams,}
    );
  }
 postApiAdminSchematicsIdToggle<TData = unknown>(id: string,
    adminToggleSchematicRequest: AdminToggleSchematicRequest, options?: HttpClientBodyOptions): Observable<TData>;
 postApiAdminSchematicsIdToggle<TData = unknown>(id: string,
    adminToggleSchematicRequest: AdminToggleSchematicRequest, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiAdminSchematicsIdToggle<TData = unknown>(id: string,
    adminToggleSchematicRequest: AdminToggleSchematicRequest, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiAdminSchematicsIdToggle<TData = unknown>(
    id: string,
    adminToggleSchematicRequest: AdminToggleSchematicRequest, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/Admin/schematics/${id}/toggle`,
      adminToggleSchematicRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/Admin/schematics/${id}/toggle`,
      adminToggleSchematicRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/Admin/schematics/${id}/toggle`,
      adminToggleSchematicRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 postApiAdminSchematicsIdResetReports<TData = unknown>(id: string, options?: HttpClientBodyOptions): Observable<TData>;
 postApiAdminSchematicsIdResetReports<TData = unknown>(id: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiAdminSchematicsIdResetReports<TData = unknown>(id: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiAdminSchematicsIdResetReports<TData = unknown>(
    id: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/Admin/schematics/${id}/reset-reports`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/Admin/schematics/${id}/reset-reports`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/Admin/schematics/${id}/reset-reports`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 deleteApiAdminSchematicsId<TData = unknown>(id: string, options?: HttpClientBodyOptions): Observable<TData>;
 deleteApiAdminSchematicsId<TData = unknown>(id: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 deleteApiAdminSchematicsId<TData = unknown>(id: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  deleteApiAdminSchematicsId<TData = unknown>(
    id: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.delete<TData>(
      `/api/Admin/schematics/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.delete<TData>(
      `/api/Admin/schematics/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.delete<TData>(
      `/api/Admin/schematics/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 getApiAdminLiveMessages<TData = LiveMessageResponse[]>( options?: HttpClientBodyOptions): Observable<TData>;
 getApiAdminLiveMessages<TData = LiveMessageResponse[]>( options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getApiAdminLiveMessages<TData = LiveMessageResponse[]>( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getApiAdminLiveMessages<TData = LiveMessageResponse[]>(
     options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/Admin/live-messages`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/Admin/live-messages`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/Admin/live-messages`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 postApiAdminLiveMessages<TData = LiveMessageResponse>(liveMessageRequest: LiveMessageRequest, options?: HttpClientBodyOptions): Observable<TData>;
 postApiAdminLiveMessages<TData = LiveMessageResponse>(liveMessageRequest: LiveMessageRequest, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiAdminLiveMessages<TData = LiveMessageResponse>(liveMessageRequest: LiveMessageRequest, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiAdminLiveMessages<TData = LiveMessageResponse>(
    liveMessageRequest: LiveMessageRequest, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/Admin/live-messages`,
      liveMessageRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/Admin/live-messages`,
      liveMessageRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/Admin/live-messages`,
      liveMessageRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 putApiAdminLiveMessagesId<TData = LiveMessageResponse>(id: number,
    liveMessageRequest: LiveMessageRequest, options?: HttpClientBodyOptions): Observable<TData>;
 putApiAdminLiveMessagesId<TData = LiveMessageResponse>(id: number,
    liveMessageRequest: LiveMessageRequest, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 putApiAdminLiveMessagesId<TData = LiveMessageResponse>(id: number,
    liveMessageRequest: LiveMessageRequest, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  putApiAdminLiveMessagesId<TData = LiveMessageResponse>(
    id: number,
    liveMessageRequest: LiveMessageRequest, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.put<TData>(
      `/api/Admin/live-messages/${id}`,
      liveMessageRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.put<TData>(
      `/api/Admin/live-messages/${id}`,
      liveMessageRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.put<TData>(
      `/api/Admin/live-messages/${id}`,
      liveMessageRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 deleteApiAdminLiveMessagesId<TData = unknown>(id: number, options?: HttpClientBodyOptions): Observable<TData>;
 deleteApiAdminLiveMessagesId<TData = unknown>(id: number, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 deleteApiAdminLiveMessagesId<TData = unknown>(id: number, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  deleteApiAdminLiveMessagesId<TData = unknown>(
    id: number, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.delete<TData>(
      `/api/Admin/live-messages/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.delete<TData>(
      `/api/Admin/live-messages/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.delete<TData>(
      `/api/Admin/live-messages/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 getApiAdminModMessages<TData = ModMessageResponse[]>( options?: HttpClientBodyOptions): Observable<TData>;
 getApiAdminModMessages<TData = ModMessageResponse[]>( options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getApiAdminModMessages<TData = ModMessageResponse[]>( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getApiAdminModMessages<TData = ModMessageResponse[]>(
     options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/Admin/mod-messages`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/Admin/mod-messages`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/Admin/mod-messages`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 postApiAdminModMessages<TData = ModMessageResponse>(modMessageRequest: ModMessageRequest, options?: HttpClientBodyOptions): Observable<TData>;
 postApiAdminModMessages<TData = ModMessageResponse>(modMessageRequest: ModMessageRequest, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiAdminModMessages<TData = ModMessageResponse>(modMessageRequest: ModMessageRequest, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiAdminModMessages<TData = ModMessageResponse>(
    modMessageRequest: ModMessageRequest, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/Admin/mod-messages`,
      modMessageRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/Admin/mod-messages`,
      modMessageRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/Admin/mod-messages`,
      modMessageRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 postApiAdminModMessagesIdToggle<TData = unknown>(id: number, options?: HttpClientBodyOptions): Observable<TData>;
 postApiAdminModMessagesIdToggle<TData = unknown>(id: number, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiAdminModMessagesIdToggle<TData = unknown>(id: number, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiAdminModMessagesIdToggle<TData = unknown>(
    id: number, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/Admin/mod-messages/${id}/toggle`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/Admin/mod-messages/${id}/toggle`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/Admin/mod-messages/${id}/toggle`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 deleteApiAdminModMessagesId<TData = unknown>(id: number, options?: HttpClientBodyOptions): Observable<TData>;
 deleteApiAdminModMessagesId<TData = unknown>(id: number, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 deleteApiAdminModMessagesId<TData = unknown>(id: number, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  deleteApiAdminModMessagesId<TData = unknown>(
    id: number, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.delete<TData>(
      `/api/Admin/mod-messages/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.delete<TData>(
      `/api/Admin/mod-messages/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.delete<TData>(
      `/api/Admin/mod-messages/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 getApiAdminStorage<TData = StorageStatsResponse>(params?: GetApiAdminStorageParams, options?: HttpClientBodyOptions): Observable<TData>;
 getApiAdminStorage<TData = StorageStatsResponse>(params?: GetApiAdminStorageParams, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getApiAdminStorage<TData = StorageStatsResponse>(params?: GetApiAdminStorageParams, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getApiAdminStorage<TData = StorageStatsResponse>(
    params?: GetApiAdminStorageParams, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    const filteredParams = filterParams({...params, ...options?.params}, new Set<string>([]));

    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/Admin/storage`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
        params: filteredParams,}
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/Admin/storage`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
        params: filteredParams,}
    );
    }

    return this.http.get<TData>(
      `/api/Admin/storage`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
        params: filteredParams,}
    );
  }
 getApiAdminTags<TData = AllowedTagResponse[]>( options?: HttpClientBodyOptions): Observable<TData>;
 getApiAdminTags<TData = AllowedTagResponse[]>( options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getApiAdminTags<TData = AllowedTagResponse[]>( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getApiAdminTags<TData = AllowedTagResponse[]>(
     options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/Admin/tags`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/Admin/tags`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/Admin/tags`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 postApiAdminTags<TData = AllowedTagResponse>(allowedTagRequest: AllowedTagRequest, options?: HttpClientBodyOptions): Observable<TData>;
 postApiAdminTags<TData = AllowedTagResponse>(allowedTagRequest: AllowedTagRequest, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiAdminTags<TData = AllowedTagResponse>(allowedTagRequest: AllowedTagRequest, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiAdminTags<TData = AllowedTagResponse>(
    allowedTagRequest: AllowedTagRequest, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/Admin/tags`,
      allowedTagRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/Admin/tags`,
      allowedTagRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/Admin/tags`,
      allowedTagRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 deleteApiAdminTagsId<TData = unknown>(id: number, options?: HttpClientBodyOptions): Observable<TData>;
 deleteApiAdminTagsId<TData = unknown>(id: number, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 deleteApiAdminTagsId<TData = unknown>(id: number, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  deleteApiAdminTagsId<TData = unknown>(
    id: number, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.delete<TData>(
      `/api/Admin/tags/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.delete<TData>(
      `/api/Admin/tags/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.delete<TData>(
      `/api/Admin/tags/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 getApiAdminModules<TData = AdminModuleListResponse>(params?: GetApiAdminModulesParams, options?: HttpClientBodyOptions): Observable<TData>;
 getApiAdminModules<TData = AdminModuleListResponse>(params?: GetApiAdminModulesParams, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getApiAdminModules<TData = AdminModuleListResponse>(params?: GetApiAdminModulesParams, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getApiAdminModules<TData = AdminModuleListResponse>(
    params?: GetApiAdminModulesParams, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    const filteredParams = filterParams({...params, ...options?.params}, new Set<string>([]));

    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/Admin/modules`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
        params: filteredParams,}
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/Admin/modules`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
        params: filteredParams,}
    );
    }

    return this.http.get<TData>(
      `/api/Admin/modules`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
        params: filteredParams,}
    );
  }
 postApiAdminModules<TData = AdminModuleResponse>(postApiAdminModulesBody: PostApiAdminModulesBody, options?: HttpClientBodyOptions): Observable<TData>;
 postApiAdminModules<TData = AdminModuleResponse>(postApiAdminModulesBody: PostApiAdminModulesBody, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiAdminModules<TData = AdminModuleResponse>(postApiAdminModulesBody: PostApiAdminModulesBody, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiAdminModules<TData = AdminModuleResponse>(
    postApiAdminModulesBody: PostApiAdminModulesBody, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {const formData = new FormData();
if(postApiAdminModulesBody.Name !== undefined) {
 formData.append(`Name`, postApiAdminModulesBody.Name);
 }
if(postApiAdminModulesBody.Description !== undefined) {
 formData.append(`Description`, postApiAdminModulesBody.Description);
 }
if(postApiAdminModulesBody.AuthorName !== undefined) {
 formData.append(`AuthorName`, postApiAdminModulesBody.AuthorName);
 }
if(postApiAdminModulesBody.LitematicFile !== undefined) {
 formData.append(`LitematicFile`, postApiAdminModulesBody.LitematicFile);
 }
if(postApiAdminModulesBody.ThumbnailFile !== undefined) {
 formData.append(`ThumbnailFile`, postApiAdminModulesBody.ThumbnailFile);
 }

    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/Admin/modules`,
      formData,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/Admin/modules`,
      formData,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/Admin/modules`,
      formData,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 putApiAdminModulesId<TData = unknown>(id: string,
    adminModuleUpdateRequest: AdminModuleUpdateRequest, options?: HttpClientBodyOptions): Observable<TData>;
 putApiAdminModulesId<TData = unknown>(id: string,
    adminModuleUpdateRequest: AdminModuleUpdateRequest, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 putApiAdminModulesId<TData = unknown>(id: string,
    adminModuleUpdateRequest: AdminModuleUpdateRequest, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  putApiAdminModulesId<TData = unknown>(
    id: string,
    adminModuleUpdateRequest: AdminModuleUpdateRequest, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.put<TData>(
      `/api/Admin/modules/${id}`,
      adminModuleUpdateRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.put<TData>(
      `/api/Admin/modules/${id}`,
      adminModuleUpdateRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.put<TData>(
      `/api/Admin/modules/${id}`,
      adminModuleUpdateRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 deleteApiAdminModulesId<TData = unknown>(id: string, options?: HttpClientBodyOptions): Observable<TData>;
 deleteApiAdminModulesId<TData = unknown>(id: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 deleteApiAdminModulesId<TData = unknown>(id: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  deleteApiAdminModulesId<TData = unknown>(
    id: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.delete<TData>(
      `/api/Admin/modules/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.delete<TData>(
      `/api/Admin/modules/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.delete<TData>(
      `/api/Admin/modules/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 getApiAdminVersions<TData = AllowedVersionResponse[]>( options?: HttpClientBodyOptions): Observable<TData>;
 getApiAdminVersions<TData = AllowedVersionResponse[]>( options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getApiAdminVersions<TData = AllowedVersionResponse[]>( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getApiAdminVersions<TData = AllowedVersionResponse[]>(
     options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/Admin/versions`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/Admin/versions`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/Admin/versions`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 postApiAdminVersions<TData = AllowedVersionResponse>(allowedVersionRequest: AllowedVersionRequest, options?: HttpClientBodyOptions): Observable<TData>;
 postApiAdminVersions<TData = AllowedVersionResponse>(allowedVersionRequest: AllowedVersionRequest, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiAdminVersions<TData = AllowedVersionResponse>(allowedVersionRequest: AllowedVersionRequest, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiAdminVersions<TData = AllowedVersionResponse>(
    allowedVersionRequest: AllowedVersionRequest, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/Admin/versions`,
      allowedVersionRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/Admin/versions`,
      allowedVersionRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/Admin/versions`,
      allowedVersionRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 deleteApiAdminVersionsId<TData = unknown>(id: number, options?: HttpClientBodyOptions): Observable<TData>;
 deleteApiAdminVersionsId<TData = unknown>(id: number, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 deleteApiAdminVersionsId<TData = unknown>(id: number, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  deleteApiAdminVersionsId<TData = unknown>(
    id: number, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.delete<TData>(
      `/api/Admin/versions/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.delete<TData>(
      `/api/Admin/versions/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.delete<TData>(
      `/api/Admin/versions/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 getApiAdminTagSuggestions<TData = TagSuggestionResponse[]>( options?: HttpClientBodyOptions): Observable<TData>;
 getApiAdminTagSuggestions<TData = TagSuggestionResponse[]>( options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getApiAdminTagSuggestions<TData = TagSuggestionResponse[]>( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getApiAdminTagSuggestions<TData = TagSuggestionResponse[]>(
     options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/Admin/tag-suggestions`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/Admin/tag-suggestions`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/Admin/tag-suggestions`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 postApiAdminTagSuggestionsIdAccept<TData = AllowedTagResponse>(id: number,
    acceptTagSuggestionRequest: AcceptTagSuggestionRequest, options?: HttpClientBodyOptions): Observable<TData>;
 postApiAdminTagSuggestionsIdAccept<TData = AllowedTagResponse>(id: number,
    acceptTagSuggestionRequest: AcceptTagSuggestionRequest, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiAdminTagSuggestionsIdAccept<TData = AllowedTagResponse>(id: number,
    acceptTagSuggestionRequest: AcceptTagSuggestionRequest, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiAdminTagSuggestionsIdAccept<TData = AllowedTagResponse>(
    id: number,
    acceptTagSuggestionRequest: AcceptTagSuggestionRequest, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/Admin/tag-suggestions/${id}/accept`,
      acceptTagSuggestionRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/Admin/tag-suggestions/${id}/accept`,
      acceptTagSuggestionRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/Admin/tag-suggestions/${id}/accept`,
      acceptTagSuggestionRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 deleteApiAdminTagSuggestionsId<TData = unknown>(id: number, options?: HttpClientBodyOptions): Observable<TData>;
 deleteApiAdminTagSuggestionsId<TData = unknown>(id: number, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 deleteApiAdminTagSuggestionsId<TData = unknown>(id: number, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  deleteApiAdminTagSuggestionsId<TData = unknown>(
    id: number, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.delete<TData>(
      `/api/Admin/tag-suggestions/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.delete<TData>(
      `/api/Admin/tag-suggestions/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.delete<TData>(
      `/api/Admin/tag-suggestions/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 getApiAdminNotifications<TData = AdminNotificationResponse[]>( options?: HttpClientBodyOptions): Observable<TData>;
 getApiAdminNotifications<TData = AdminNotificationResponse[]>( options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getApiAdminNotifications<TData = AdminNotificationResponse[]>( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getApiAdminNotifications<TData = AdminNotificationResponse[]>(
     options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/Admin/notifications`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/Admin/notifications`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/Admin/notifications`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 postApiAdminNotificationsIdRead<TData = unknown>(id: number, options?: HttpClientBodyOptions): Observable<TData>;
 postApiAdminNotificationsIdRead<TData = unknown>(id: number, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiAdminNotificationsIdRead<TData = unknown>(id: number, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiAdminNotificationsIdRead<TData = unknown>(
    id: number, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/Admin/notifications/${id}/read`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/Admin/notifications/${id}/read`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/Admin/notifications/${id}/read`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 postApiAdminNotificationsIdUnread<TData = unknown>(id: number, options?: HttpClientBodyOptions): Observable<TData>;
 postApiAdminNotificationsIdUnread<TData = unknown>(id: number, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiAdminNotificationsIdUnread<TData = unknown>(id: number, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiAdminNotificationsIdUnread<TData = unknown>(
    id: number, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/Admin/notifications/${id}/unread`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/Admin/notifications/${id}/unread`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/Admin/notifications/${id}/unread`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 deleteApiAdminNotificationsId<TData = unknown>(id: number, options?: HttpClientBodyOptions): Observable<TData>;
 deleteApiAdminNotificationsId<TData = unknown>(id: number, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 deleteApiAdminNotificationsId<TData = unknown>(id: number, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  deleteApiAdminNotificationsId<TData = unknown>(
    id: number, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.delete<TData>(
      `/api/Admin/notifications/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.delete<TData>(
      `/api/Admin/notifications/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.delete<TData>(
      `/api/Admin/notifications/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 postApiAdminFaq<TData = FaqResponse>(faqCreateRequest: FaqCreateRequest, options?: HttpClientBodyOptions): Observable<TData>;
 postApiAdminFaq<TData = FaqResponse>(faqCreateRequest: FaqCreateRequest, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiAdminFaq<TData = FaqResponse>(faqCreateRequest: FaqCreateRequest, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiAdminFaq<TData = FaqResponse>(
    faqCreateRequest: FaqCreateRequest, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/Admin/faq`,
      faqCreateRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/Admin/faq`,
      faqCreateRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/Admin/faq`,
      faqCreateRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 putApiAdminFaqId<TData = FaqResponse>(id: number,
    faqUpdateRequest: FaqUpdateRequest, options?: HttpClientBodyOptions): Observable<TData>;
 putApiAdminFaqId<TData = FaqResponse>(id: number,
    faqUpdateRequest: FaqUpdateRequest, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 putApiAdminFaqId<TData = FaqResponse>(id: number,
    faqUpdateRequest: FaqUpdateRequest, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  putApiAdminFaqId<TData = FaqResponse>(
    id: number,
    faqUpdateRequest: FaqUpdateRequest, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.put<TData>(
      `/api/Admin/faq/${id}`,
      faqUpdateRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.put<TData>(
      `/api/Admin/faq/${id}`,
      faqUpdateRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.put<TData>(
      `/api/Admin/faq/${id}`,
      faqUpdateRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 deleteApiAdminFaqId<TData = unknown>(id: number, options?: HttpClientBodyOptions): Observable<TData>;
 deleteApiAdminFaqId<TData = unknown>(id: number, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 deleteApiAdminFaqId<TData = unknown>(id: number, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  deleteApiAdminFaqId<TData = unknown>(
    id: number, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.delete<TData>(
      `/api/Admin/faq/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.delete<TData>(
      `/api/Admin/faq/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.delete<TData>(
      `/api/Admin/faq/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 getApiAdminTickets<TData = unknown>(params?: GetApiAdminTicketsParams, options?: HttpClientBodyOptions): Observable<TData>;
 getApiAdminTickets<TData = unknown>(params?: GetApiAdminTicketsParams, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getApiAdminTickets<TData = unknown>(params?: GetApiAdminTicketsParams, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getApiAdminTickets<TData = unknown>(
    params?: GetApiAdminTicketsParams, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    const filteredParams = filterParams({...params, ...options?.params}, new Set<string>([]));

    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/Admin/tickets`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
        params: filteredParams,}
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/Admin/tickets`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
        params: filteredParams,}
    );
    }

    return this.http.get<TData>(
      `/api/Admin/tickets`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
        params: filteredParams,}
    );
  }
 getApiAdminTicketsId<TData = ContactTicketResponse>(id: number, options?: HttpClientBodyOptions): Observable<TData>;
 getApiAdminTicketsId<TData = ContactTicketResponse>(id: number, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getApiAdminTicketsId<TData = ContactTicketResponse>(id: number, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getApiAdminTicketsId<TData = ContactTicketResponse>(
    id: number, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/Admin/tickets/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/Admin/tickets/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/Admin/tickets/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 deleteApiAdminTicketsId<TData = unknown>(id: number, options?: HttpClientBodyOptions): Observable<TData>;
 deleteApiAdminTicketsId<TData = unknown>(id: number, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 deleteApiAdminTicketsId<TData = unknown>(id: number, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  deleteApiAdminTicketsId<TData = unknown>(
    id: number, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.delete<TData>(
      `/api/Admin/tickets/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.delete<TData>(
      `/api/Admin/tickets/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.delete<TData>(
      `/api/Admin/tickets/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 postApiAdminTicketsIdReply<TData = ContactTicketResponse>(id: number, ticketReplyRequest: TicketReplyRequest, options?: HttpClientBodyOptions): Observable<TData>;
 postApiAdminTicketsIdReply<TData = ContactTicketResponse>(id: number, ticketReplyRequest: TicketReplyRequest, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiAdminTicketsIdReply<TData = ContactTicketResponse>(id: number, ticketReplyRequest: TicketReplyRequest, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiAdminTicketsIdReply<TData = ContactTicketResponse>(
    id: number, ticketReplyRequest: TicketReplyRequest, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/Admin/tickets/${id}/reply`,
      ticketReplyRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/Admin/tickets/${id}/reply`,
      ticketReplyRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/Admin/tickets/${id}/reply`,
      ticketReplyRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 postApiAdminTicketsIdRead<TData = unknown>(id: number, options?: HttpClientBodyOptions): Observable<TData>;
 postApiAdminTicketsIdRead<TData = unknown>(id: number, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiAdminTicketsIdRead<TData = unknown>(id: number, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiAdminTicketsIdRead<TData = unknown>(
    id: number, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/Admin/tickets/${id}/read`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/Admin/tickets/${id}/read`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/Admin/tickets/${id}/read`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 getApiAdminServerLogs<TData = unknown>(params?: GetApiAdminServerLogsParams, options?: HttpClientBodyOptions): Observable<TData>;
 getApiAdminServerLogs<TData = unknown>(params?: GetApiAdminServerLogsParams, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getApiAdminServerLogs<TData = unknown>(params?: GetApiAdminServerLogsParams, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getApiAdminServerLogs<TData = unknown>(
    params?: GetApiAdminServerLogsParams, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    const filteredParams = filterParams({...params, ...options?.params}, new Set<string>([]));

    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/Admin/server-logs`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
        params: filteredParams,}
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/Admin/server-logs`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
        params: filteredParams,}
    );
    }

    return this.http.get<TData>(
      `/api/Admin/server-logs`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
        params: filteredParams,}
    );
  }
 deleteApiAdminServerLogs<TData = unknown>( options?: HttpClientBodyOptions): Observable<TData>;
 deleteApiAdminServerLogs<TData = unknown>( options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 deleteApiAdminServerLogs<TData = unknown>( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  deleteApiAdminServerLogs<TData = unknown>(
     options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.delete<TData>(
      `/api/Admin/server-logs`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.delete<TData>(
      `/api/Admin/server-logs`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.delete<TData>(
      `/api/Admin/server-logs`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 deleteApiAdminServerLogsId<TData = unknown>(id: number, options?: HttpClientBodyOptions): Observable<TData>;
 deleteApiAdminServerLogsId<TData = unknown>(id: number, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 deleteApiAdminServerLogsId<TData = unknown>(id: number, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  deleteApiAdminServerLogsId<TData = unknown>(
    id: number, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.delete<TData>(
      `/api/Admin/server-logs/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.delete<TData>(
      `/api/Admin/server-logs/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.delete<TData>(
      `/api/Admin/server-logs/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
};

export type GetApiAdminUsersClientResult = NonNullable<AdminUserListResponse>
export type GetApiAdminUsersIdClientResult = NonNullable<AdminUserDetailResponse>
export type PostApiAdminUsersIdStatusClientResult = NonNullable<unknown>
export type PostApiAdminUsersIdRoleClientResult = NonNullable<unknown>
export type PostApiAdminUsersIdBadgeClientResult = NonNullable<unknown>
export type PostApiAdminUsersIdQuotaClientResult = NonNullable<unknown>
export type PostApiAdminUsersIdNoteClientResult = NonNullable<unknown>
export type DeleteApiAdminUsersIdApiKeyClientResult = NonNullable<unknown>
export type DeleteApiAdminUsersIdSaveKeyClientResult = NonNullable<unknown>
export type PostApiAdminUsersLoginAsClientResult = NonNullable<LoginResponse>
export type PostApiAdminUsersIdResetReportsClientResult = NonNullable<unknown>
export type GetApiAdminSchematicsClientResult = NonNullable<AdminSchematicListResponse>
export type PostApiAdminSchematicsIdToggleClientResult = NonNullable<unknown>
export type PostApiAdminSchematicsIdResetReportsClientResult = NonNullable<unknown>
export type DeleteApiAdminSchematicsIdClientResult = NonNullable<unknown>
export type GetApiAdminLiveMessagesClientResult = NonNullable<LiveMessageResponse[]>
export type PostApiAdminLiveMessagesClientResult = NonNullable<LiveMessageResponse>
export type PutApiAdminLiveMessagesIdClientResult = NonNullable<LiveMessageResponse>
export type DeleteApiAdminLiveMessagesIdClientResult = NonNullable<unknown>
export type GetApiAdminModMessagesClientResult = NonNullable<ModMessageResponse[]>
export type PostApiAdminModMessagesClientResult = NonNullable<ModMessageResponse>
export type PostApiAdminModMessagesIdToggleClientResult = NonNullable<unknown>
export type DeleteApiAdminModMessagesIdClientResult = NonNullable<unknown>
export type GetApiAdminStorageClientResult = NonNullable<StorageStatsResponse>
export type GetApiAdminTagsClientResult = NonNullable<AllowedTagResponse[]>
export type PostApiAdminTagsClientResult = NonNullable<AllowedTagResponse>
export type DeleteApiAdminTagsIdClientResult = NonNullable<unknown>
export type GetApiAdminModulesClientResult = NonNullable<AdminModuleListResponse>
export type PostApiAdminModulesClientResult = NonNullable<AdminModuleResponse>
export type PutApiAdminModulesIdClientResult = NonNullable<unknown>
export type DeleteApiAdminModulesIdClientResult = NonNullable<unknown>
export type GetApiAdminVersionsClientResult = NonNullable<AllowedVersionResponse[]>
export type PostApiAdminVersionsClientResult = NonNullable<AllowedVersionResponse>
export type DeleteApiAdminVersionsIdClientResult = NonNullable<unknown>
export type GetApiAdminTagSuggestionsClientResult = NonNullable<TagSuggestionResponse[]>
export type PostApiAdminTagSuggestionsIdAcceptClientResult = NonNullable<AllowedTagResponse>
export type DeleteApiAdminTagSuggestionsIdClientResult = NonNullable<unknown>
export type GetApiAdminNotificationsClientResult = NonNullable<AdminNotificationResponse[]>
export type PostApiAdminNotificationsIdReadClientResult = NonNullable<unknown>
export type PostApiAdminNotificationsIdUnreadClientResult = NonNullable<unknown>
export type DeleteApiAdminNotificationsIdClientResult = NonNullable<unknown>
export type PostApiAdminFaqClientResult = NonNullable<FaqResponse>
export type PutApiAdminFaqIdClientResult = NonNullable<FaqResponse>
export type DeleteApiAdminFaqIdClientResult = NonNullable<unknown>
export type GetApiAdminTicketsClientResult = NonNullable<unknown>
export type GetApiAdminTicketsIdClientResult = NonNullable<ContactTicketResponse>
export type DeleteApiAdminTicketsIdClientResult = NonNullable<unknown>
export type PostApiAdminTicketsIdReadClientResult = NonNullable<unknown>
export type PostApiAdminTicketsIdReplyClientResult = NonNullable<ContactTicketResponse>
export type GetApiAdminServerLogsClientResult = NonNullable<unknown>
export type DeleteApiAdminServerLogsClientResult = NonNullable<unknown>
export type DeleteApiAdminServerLogsIdClientResult = NonNullable<unknown>
