/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Backend | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient,
  HttpHeaders
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpParams,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  LoginRequest,
  LoginResponse,
  RefreshTokenRequest,
  VerifyLoginRequest
} from './generated.schemas';




interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
        | HttpParams
      | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: {includeHeaders?: string[]} | boolean;
}





@Injectable({ providedIn: 'root' })
export class AuthService {
  private readonly http = inject(HttpClient);
 postApiAuthLogin<TData = LoginResponse>(loginRequest: LoginRequest, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiAuthLogin<TData = LoginResponse>(loginRequest: LoginRequest, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiAuthLogin<TData = LoginResponse>(loginRequest: LoginRequest, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiAuthLogin<TData = LoginResponse>(
    loginRequest: LoginRequest, options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/Auth/login`,
      loginRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/Auth/login`,
      loginRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/Auth/login`,
      loginRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 postApiAuthVerifyLogin<TData = LoginResponse>(verifyLoginRequest: VerifyLoginRequest, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiAuthVerifyLogin<TData = LoginResponse>(verifyLoginRequest: VerifyLoginRequest, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiAuthVerifyLogin<TData = LoginResponse>(verifyLoginRequest: VerifyLoginRequest, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiAuthVerifyLogin<TData = LoginResponse>(
    verifyLoginRequest: VerifyLoginRequest, options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/Auth/verify-login`,
      verifyLoginRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/Auth/verify-login`,
      verifyLoginRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/Auth/verify-login`,
      verifyLoginRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 postApiAuthRefresh<TData = LoginResponse>(refreshTokenRequest: RefreshTokenRequest, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiAuthRefresh<TData = LoginResponse>(refreshTokenRequest: RefreshTokenRequest, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiAuthRefresh<TData = LoginResponse>(refreshTokenRequest: RefreshTokenRequest, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiAuthRefresh<TData = LoginResponse>(
    refreshTokenRequest: RefreshTokenRequest, options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/Auth/refresh`,
      refreshTokenRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/Auth/refresh`,
      refreshTokenRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/Auth/refresh`,
      refreshTokenRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 postApiAuthRevoke<TData = unknown>(refreshTokenRequest: RefreshTokenRequest, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiAuthRevoke<TData = unknown>(refreshTokenRequest: RefreshTokenRequest, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiAuthRevoke<TData = unknown>(refreshTokenRequest: RefreshTokenRequest, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiAuthRevoke<TData = unknown>(
    refreshTokenRequest: RefreshTokenRequest, options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/Auth/revoke`,
      refreshTokenRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/Auth/revoke`,
      refreshTokenRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/Auth/revoke`,
      refreshTokenRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
}

