/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Backend | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient,
  HttpHeaders,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpParams
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  PostApiContactBody
} from './generated.schemas';




interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
        | HttpParams
      | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: {includeHeaders?: string[]} | boolean;
  readonly timeout?: number;
}

type HttpClientBodyOptions = HttpClientOptions & {
  readonly observe?: 'body';
};

type HttpClientEventOptions = HttpClientOptions & {
  readonly observe: 'events';
};

type HttpClientResponseOptions = HttpClientOptions & {
  readonly observe: 'response';
};

type HttpClientObserveOptions = HttpClientOptions & {
  readonly observe?: 'body' | 'events' | 'response';
};







@Injectable({ providedIn: 'root' })
export class ContactService {
  private readonly http = inject(HttpClient);
 postApiContact<TData = unknown>(postApiContactBody: PostApiContactBody, options?: HttpClientBodyOptions): Observable<TData>;
 postApiContact<TData = unknown>(postApiContactBody: PostApiContactBody, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiContact<TData = unknown>(postApiContactBody: PostApiContactBody, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiContact<TData = unknown>(
    postApiContactBody: PostApiContactBody, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {const formData = new FormData();
if(postApiContactBody.Title !== undefined) {
 formData.append(`Title`, postApiContactBody.Title);
 }
if(postApiContactBody.Description !== undefined) {
 formData.append(`Description`, postApiContactBody.Description);
 }
if(postApiContactBody.Contact !== undefined) {
 formData.append(`Contact`, postApiContactBody.Contact);
 }
if(postApiContactBody.Images !== undefined) {
 postApiContactBody.Images.forEach(value => formData.append(`Images`, value));
 }
if(postApiContactBody.CaptchaId !== undefined) {
 formData.append(`CaptchaId`, postApiContactBody.CaptchaId);
 }
if(postApiContactBody.CaptchaPositions !== undefined) {
 formData.append(`CaptchaPositions`, postApiContactBody.CaptchaPositions);
 }

    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/Contact`,
      formData,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/Contact`,
      formData,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/Contact`,
      formData,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
};

