/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Backend | v1
 * OpenAPI spec version: 1.0.0
 */
export interface AddSecurityKeyRequest {
  keyName: string;
}

export interface AdminLoginAsRequest {
  userId: string;
}

export interface AdminSchematicResponse {
  id: string;
  name: string;
  status: string;
  visibility: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  reportCount: number | string;
  username: string;
  publishDate: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  likesCount: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  downloadCount: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  viewCount: number | string;
}

export interface AdminSchematicListResponse {
  items: AdminSchematicResponse[];
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  totalCount: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  page: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  pageSize: number | string;
}

export interface AdminToggleSchematicRequest {
  /** @nullable */
  status: string | null;
  /** @nullable */
  visibility: string | null;
}

export interface SocialLinkResponse {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id: number | string;
  platform: string;
  url: string;
}

export interface AdminUserSchematicResponse {
  id: string;
  name: string;
  status: string;
  visibility: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  reportCount: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  downloadCount: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  viewCount: number | string;
  publishDate: string;
}

export interface AdminUserDetailResponse {
  id: string;
  username: string;
  /** @nullable */
  email: string | null;
  registrationDate: string;
  role: string;
  /** @nullable */
  badge: string | null;
  status: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  reportCount: number | string;
  /** @nullable */
  biographie: string | null;
  /** @nullable */
  filePath: string | null;
  /** @nullable */
  coverImagePath: string | null;
  socialLinks: SocialLinkResponse[];
  /** @nullable */
  minecraftUsername: string | null;
  /** @nullable */
  minecraftUUID: string | null;
  /** @nullable */
  isMinecraftLinked: boolean | null;
  /** @nullable */
  minecraftLinkDate: string | null;
  /** @nullable */
  discordUsername: string | null;
  /** @nullable */
  discordId: string | null;
  /** @nullable */
  isDiscordLinked: boolean | null;
  /** @nullable */
  discordLinkDate: string | null;
  hasApiKey: boolean;
  hasSaveKey: boolean;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  storageQuotaGb: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  storageUsedMb: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  saveCount: number | string;
  schematics: AdminUserSchematicResponse[];
}

export interface AdminUserResponse {
  id: string;
  username: string;
  role: string;
  status: string;
  /** @nullable */
  suspensionEndDate: string | null;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  reportCount: number | string;
  registrationDate: string;
  /** @nullable */
  email: string | null;
}

export interface AdminUserListResponse {
  items: AdminUserResponse[];
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  totalCount: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  page: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  pageSize: number | string;
}

export interface AllowedTagRequest {
  name: string;
}

export interface AllowedTagResponse {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id: number | string;
  name: string;
}

export interface AllowedVersionRequest {
  name: string;
}

export interface AllowedVersionResponse {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id: number | string;
  name: string;
}

export interface AssertionResponse {
  authenticatorData: unknown;
  signature: unknown;
  clientDataJSON: unknown;
  userHandle?: unknown;
}

export interface AttestationResponse {
  attestationObject: unknown;
  clientDataJSON: unknown;
  /** @nullable */
  transports: unknown[] | null;
}

export interface CredentialPropertiesOutput {
  rk?: boolean;
  /** @nullable */
  authenticatorDisplayName?: string | null;
}

export interface AuthenticationExtensionsPRFValues {
  first: unknown;
  second?: unknown;
}

export interface AuthenticationExtensionsPRFOutputs {
  enabled?: boolean;
  results?: AuthenticationExtensionsPRFValues;
}

export interface AuthenticationExtensionsLargeBlobOutputs {
  supported?: boolean;
  blob?: unknown;
  written?: boolean;
}

export interface CredentialProtectionPolicy {}

export interface AuthenticationExtensionsClientOutputs {
  /** @nullable */
  'example.extension.bool'?: boolean | null;
  appid?: boolean;
  /** @nullable */
  exts?: string[] | null;
  /** @nullable */
  uvm?: ((number | string)[])[] | null;
  credProps?: null | CredentialPropertiesOutput;
  prf?: null | AuthenticationExtensionsPRFOutputs;
  largeBlob?: null | AuthenticationExtensionsLargeBlobOutputs;
  credProtect?: null | CredentialProtectionPolicy;
}

export interface PublicKeyCredentialType {}

export interface AuthenticatorAssertionRawResponse {
  /** @nullable */
  id: string | null;
  rawId: unknown;
  response?: AssertionResponse;
  type: PublicKeyCredentialType;
  extensions?: AuthenticationExtensionsClientOutputs;
  clientExtensionResults: AuthenticationExtensionsClientOutputs;
}

export interface AuthenticatorAttestationRawResponse {
  /** @nullable */
  id: string | null;
  rawId: unknown;
  type: PublicKeyCredentialType;
  response: AttestationResponse;
  extensions?: AuthenticationExtensionsClientOutputs;
  clientExtensionResults: AuthenticationExtensionsClientOutputs;
}

export type Badge = number;

export interface CaptchaShape {
  id: string;
  type: string;
  color: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  x: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  y: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  size: number | string;
  isCutout: boolean;
  isDraggable: boolean;
}

export interface CaptchaChallenge {
  captchaId: string;
  shapes: CaptchaShape[];
  instructions: string;
}

export interface CaptchaTrackPointDto {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  x: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  y: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  timestamp: number | string;
}

export interface CaptchaPositionDto {
  shapeId: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  x: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  y: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  timestamp: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  dragDuration: number | string;
  dragPath: CaptchaTrackPointDto[];
}

export interface ChangeUserBadgeRequest {
  /** @nullable */
  badge: string | null;
}

export interface ChangeUserQuotaRequest {
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  quotaGb: number | string;
}

export interface ChangeUserRoleRequest {
  role: string;
}

export interface ChangeUserStatusRequest {
  status: string;
  /** @nullable */
  suspensionEndDate: string | null;
}

export interface ConfirmPasswordResetRequest {
  email: string;
  code: string;
  newPassword: string;
}

export interface ConfirmProfileUpdateRequest {
  code: string;
  email: string;
}

export interface ConfirmRegisterRequest {
  username: string;
  email: string;
  password: string;
  passwordConfirm: string;
  code: string;
}

export interface CreateShortUrlRequest {
  longUrl: string;
  /** @nullable */
  screenshotPath: string | null;
}

export interface EmailAvailableResponse {
  email: string;
  isAvailable: boolean;
}

export type IFormFile = Blob;

export type IFormFileCollection = IFormFile[];

export interface JsonElement {}

export interface LeaderboardUserResponse {
  id: string;
  username: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  score: number | string;
  /** @nullable */
  filePath: string | null;
  badge: null | Badge;
  /** @nullable */
  lastWin: string | null;
}

export interface LeaderboardResponse {
  top10: LeaderboardUserResponse[];
  last3Winners: LeaderboardUserResponse[];
}

export interface LikeResponse {
  isLiked: boolean;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  likesCount: number | string;
}

export interface LinkMinecraftRequest {
  code: string;
  minecraftUUID: string;
  /** @nullable */
  minecraftUsername: string | null;
}

export interface LiveMessageRequest {
  message: string;
  type: string;
}

export interface LiveMessageResponse {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id: number | string;
  message: string;
  type: string;
  time: string;
}

export interface LoginRequest {
  login: string;
  password: string;
  /** @nullable */
  captchaId: string | null;
  /** @nullable */
  captchaPositions: CaptchaPositionDto[] | null;
}

export interface LoginResponse {
  token: string;
  refreshToken: string;
  username: string;
  role: string;
  /** @nullable */
  filePath: string | null;
}

export interface ModListItemResponse {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id: number | string;
  title: string;
  description: string;
  releaseType: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  downloadCount: number | string;
  gameVersion: string;
  platform: string;
  /** @nullable */
  filePath: string | null;
  /** @nullable */
  imagePath: string | null;
}

export interface ModMessageRequest {
  message: string;
  type: string;
}

export interface ModMessageResponse {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id: number | string;
  message: string;
  type: string;
  time: string;
  isActive: boolean;
}

export interface OwnProfileResponse {
  id: string;
  username: string;
  email: string;
  /** @nullable */
  filePath: string | null;
  /** @nullable */
  fileType: string | null;
  /** @nullable */
  coverImagePath: string | null;
  /** @nullable */
  badge: string | null;
  /** @nullable */
  biographie: string | null;
  registrationDate: string;
  /** @nullable */
  minecraftUsername: string | null;
  /** @nullable */
  isMinecraftLinked: boolean | null;
  /** @nullable */
  discordUsername: string | null;
  /** @nullable */
  isDiscordLinked: boolean | null;
  hasSecurityKeys: boolean;
  socialLinks: SocialLinkResponse[];
}

export interface ProblemDetails {
  /** @nullable */
  type?: string | null;
  /** @nullable */
  title?: string | null;
  /**
   * @nullable
   * @pattern ^-?(?:0|[1-9]\d*)$
   */
  status?: number | string | null;
  /** @nullable */
  detail?: string | null;
  /** @nullable */
  instance?: string | null;
}

export interface SchematicListItemResponse {
  id: string;
  name: string;
  /** @nullable */
  description: string | null;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  likesCount: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  downloadCount: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  viewCount: number | string;
  username: string;
  /** @nullable */
  filePath: string | null;
  /** @nullable */
  fileType: string | null;
  authorName: string;
  authorId: string;
  schematicType: string;
  /** @nullable */
  forked: string | null;
  isLiked: boolean;
  publishDate: string;
  tags: string[];
  versions: string[];
}

export interface PublicUserListItemResponse {
  id: string;
  username: string;
  /** @nullable */
  filePath: string | null;
  isLiked: boolean;
  /** @nullable */
  isMinecraftLinked: boolean | null;
  /** @nullable */
  minecraftUsername: string | null;
  /** @nullable */
  isDiscordLinked: boolean | null;
  /** @nullable */
  discordUsername: string | null;
}

export interface PublicProfileResponse {
  username: string;
  /** @nullable */
  filePath: string | null;
  /** @nullable */
  coverImagePath: string | null;
  /** @nullable */
  badge: string | null;
  /** @nullable */
  minecraftUsername: string | null;
  /** @nullable */
  discordUsername: string | null;
  registrationDate: string;
  /** @nullable */
  biographie: string | null;
  socialLinks: SocialLinkResponse[];
  schematics: SchematicListItemResponse[];
  likedSchematics: SchematicListItemResponse[];
  likedUsers: PublicUserListItemResponse[];
}

export interface RefreshTokenRequest {
  refreshToken: string;
}

export interface RegenerateSaveKeyResponse {
  saveKey: string;
}

export interface RegisterRequest {
  username: string;
  email: string;
  password: string;
  passwordConfirm: string;
  /** @nullable */
  captchaId: string | null;
  /** @nullable */
  captchaPositions: CaptchaPositionDto[] | null;
}

export interface RegisterResponse {
  token: string;
  refreshToken: string;
  username: string;
  role: string;
}

export interface ReportSchematicRequest {
  schematicId: string;
  /** @nullable */
  reason: string | null;
}

export interface ReportUserRequest {
  userId: string;
  /** @nullable */
  reason: string | null;
}

export interface RequestPasswordResetRequest {
  email: string;
}

export interface RequestProfileUpdateRequest {
  email: string;
}

export interface SaveListItemResponse {
  id: string;
  worldName: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  fileSizeBytes: number | string;
  createdAt: string;
  updatedAt: string;
}

export interface SaveQuotaResponse {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  usedSpaceBytes: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  totalSpaceBytes: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  remainingSpaceBytes: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  usedSpacePercentage: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  saveCount: number | string;
}

export interface SchematicPictureResponse {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id: number | string;
  /** @nullable */
  filePath: string | null;
  /** @nullable */
  fileType: string | null;
}

export interface SchematicFileResponse {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id: number | string;
  name: string;
  /** @nullable */
  filePath: string | null;
  /** @nullable */
  blockList: string | null;
}

export interface SchematicDetailResponse {
  id: string;
  name: string;
  /** @nullable */
  description: string | null;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  likesCount: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  downloadCount: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  viewCount: number | string;
  username: string;
  userId: string;
  /** @nullable */
  filePath: string | null;
  /** @nullable */
  fileType: string | null;
  authorName: string;
  authorId: string;
  schematicType: string;
  /** @nullable */
  forked: string | null;
  visibility: string;
  isLiked: boolean;
  publishDate: string;
  /** @nullable */
  downloadLinkMediaFire: string | null;
  /** @nullable */
  youtubeLink: string | null;
  pictures: SchematicPictureResponse[];
  files: SchematicFileResponse[];
  tags: string[];
  versions: string[];
}

export interface SchematicListResponse {
  items: SchematicListItemResponse[];
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  totalCount: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  page: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  pageSize: number | string;
}

export interface SecurityKeyResponse {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id: number | string;
  keyName: string;
  dateAdded: string;
  /** @nullable */
  lastUsed: string | null;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  useCount: number | string;
}

export interface ServerLinkDiscordRequest {
  code: string;
  discordId: string;
  /** @nullable */
  discordUsername: string | null;
}

export interface ServerLinkMinecraftRequest {
  code: string;
  minecraftUUID: string;
  /** @nullable */
  minecraftUsername: string | null;
}

export interface ShortUrlResponse {
  id: string;
  longUrl: string;
  shortUrl: string;
  createdAt: string;
}

export interface SocialLinkRequest {
  platform: string;
  url: string;
}

export interface UserStorageResponse {
  userId: string;
  username: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  saveCount: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  totalBytes: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  totalMb: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  quotaGb: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  percentageOfQuota: number | string;
}

export interface StorageStatsResponse {
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  totalDiskGb: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  freeDiskGb: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  usedDiskGb: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  diskUsagePercent: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  currentSaveUsageGb: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  maxPotentialGb: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  totalUsersWithSaves: number | string;
  userStorages: UserStorageResponse[];
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  totalCount: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  page: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  pageSize: number | string;
}

export interface UpdateProfileRequest {
  /** @nullable */
  username: string | null;
  /** @nullable */
  bio: string | null;
}

export interface UserContentResponse {
  schematics: SchematicListItemResponse[];
  likedSchematics: SchematicListItemResponse[];
  likedUsers: PublicUserListItemResponse[];
}

export interface UserLikeResponse {
  isLiked: boolean;
}

export interface UserListItemResponse {
  id: string;
  username: string;
  /** @nullable */
  email: string | null;
  role: string;
  status: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  reportCount: number | string;
  registrationDate: string;
  /** @nullable */
  filePath: string | null;
}

export interface UserListResponse {
  items: UserListItemResponse[];
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  totalCount: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  page: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  pageSize: number | string;
}

export interface UsernameAvailableResponse {
  username: string;
  isAvailable: boolean;
}

export interface UserProfileResponse {
  id: string;
  username: string;
  /** @nullable */
  biographie: string | null;
  /** @nullable */
  filePath: string | null;
  /** @nullable */
  coverImagePath: string | null;
  badge: null | Badge;
  registrationDate: string;
  isLiked: boolean;
  /** @nullable */
  isMinecraftLinked: boolean | null;
  /** @nullable */
  minecraftUsername: string | null;
  /** @nullable */
  isDiscordLinked: boolean | null;
  /** @nullable */
  discordUsername: string | null;
  socialLinks: SocialLinkResponse[];
}

export interface ValidateCodeRequest {
  code: string;
}

export interface VerifyLoginRequest {
  login: string;
  code: string;
}

export interface VerifyPasswordRequest {
  password: string;
}

export type GetApiAdminUsersParams = {
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
page?: number | string;
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
pageSize?: number | string;
search?: string;
sort?: string;
direction?: string;
newestOnly?: boolean;
};

export type GetApiAdminSchematicsParams = {
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
page?: number | string;
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
pageSize?: number | string;
search?: string;
sort?: string;
direction?: string;
};

export type GetApiAdminStorageParams = {
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
page?: number | string;
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
pageSize?: number | string;
search?: string;
sort?: string;
direction?: string;
};

export type PostApiModsBody = {
  Title?: string;
  Description?: string;
  ReleaseType?: string;
  GameVersion?: string;
  Platform?: string;
  File?: IFormFile;
  Image?: IFormFile;
};

export type PutApiModsIdBody = {
  Title?: string;
  Description?: string;
  ReleaseType?: string;
  GameVersion?: string;
  Platform?: string;
  File?: IFormFile;
  Image?: IFormFile;
};

export type GetApiSchematicsParams = {
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
page?: number | string;
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
pageSize?: number | string;
search?: string;
tag?: string;
type?: string;
version?: string;
sort?: string;
direction?: string;
userId?: string;
};

export type PostApiSchematicsBody = {
  Name?: string;
  Description?: string;
  AuthorName?: string;
  SchematicsPictureFiles?: IFormFileCollection;
  LitematicFiles?: IFormFileCollection;
  DownloadLinkMediaFire?: string;
  YoutubeLink?: string;
  Tags?: string;
  Versions?: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  CoverImageIndex?: number | string;
  SchematicType?: string;
  Visibility?: string;
};

export type PutApiSchematicsIdBody = {
  Name?: string;
  Description?: string;
  NewPictureFiles?: IFormFileCollection;
  NewLitematicFiles?: IFormFileCollection;
  RemovePictureIds?: string;
  RemoveFileIds?: string;
  DownloadLinkMediaFire?: string;
  YoutubeLink?: string;
  Tags?: string;
  Versions?: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  CoverImageIndex?: number | string;
  PictureOrder?: string;
  FileOrder?: string;
  SchematicType?: string;
  Visibility?: string;
};

export type GetApiSchematicsSearchNamesParams = {
q?: string;
};

export type GetApiSchematicsSearchUsersParams = {
q?: string;
};

export type GetApiSchematicsSearchTagsParams = {
q?: string;
};

export type GetApiSchematicsSearchAuthorsParams = {
q?: string;
};

export type GetApiSchematicsUserUsernameContentParams = {
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
page?: number | string;
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
pageSize?: number | string;
};

export type PostApiSecurityKeysRegisterParams = {
sessionId?: string;
};

export type PostApiSecurityKeysLoginParams = {
sessionId?: string;
};

export type GetApiUserBrowseParams = {
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
page?: number | string;
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
pageSize?: number | string;
search?: string;
role?: string;
status?: string;
sort?: string;
direction?: string;
newestOnly?: boolean;
};

export type GetApiUserBrowseSearchParams = {
q?: string;
};

export type PutApiUsersMeProfilePictureBody = {
  file?: IFormFile;
};

export type PutApiUsersMeCoverImageBody = {
  file?: IFormFile;
};

