/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Backend | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient,
  HttpHeaders,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpParams
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  GetApiGitReposRepoIdBranchesBranchNameCommitsParams,
  GetApiGitReposRepoIdReleasesParams,
  GetApiGitReposUserUsernameParams,
  GitCommitListResponse,
  GitReleaseListResponse,
  GitReleaseResponse,
  GitRepoDetailResponse,
  GitRepoListResponse,
  PostApiGitReposRepoIdReleasesBody,
  PutApiGitReposRepoIdThumbnailBody
} from './generated.schemas';




interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
        | HttpParams
      | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: {includeHeaders?: string[]} | boolean;
  readonly timeout?: number;
}

type HttpClientBodyOptions = HttpClientOptions & {
  readonly observe?: 'body';
};

type HttpClientEventOptions = HttpClientOptions & {
  readonly observe: 'events';
};

type HttpClientResponseOptions = HttpClientOptions & {
  readonly observe: 'response';
};

type HttpClientObserveOptions = HttpClientOptions & {
  readonly observe?: 'body' | 'events' | 'response';
};

type AngularHttpParamValue = string | number | boolean | Array<string | number | boolean>;
type AngularHttpParamValueWithNullable = AngularHttpParamValue | null;

function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys?: ReadonlySet<string>,
  preserveRequiredNullables?: false,
  passthroughKeys?: undefined,
): Record<string, AngularHttpParamValue>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> | undefined,
  preserveRequiredNullables: true,
  passthroughKeys?: undefined,
): Record<string, AngularHttpParamValueWithNullable>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> | undefined,
  preserveRequiredNullables: boolean | undefined,
  passthroughKeys: ReadonlySet<string>,
): Record<string, unknown>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> = new Set(),
  preserveRequiredNullables = false,
  passthroughKeys: ReadonlySet<string> = new Set(),
): Record<string, unknown> {
  const filteredParams: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(params)) {
    if (passthroughKeys.has(key)) {
      if (value !== undefined) {
        filteredParams[key] = value;
      }
      continue;
    }
    if (Array.isArray(value)) {
      const filtered = value.filter(
        (item) =>
          item != null &&
          (typeof item === 'string' ||
            typeof item === 'number' ||
            typeof item === 'boolean'),
      ) as Array<string | number | boolean>;
      if (filtered.length) {
        filteredParams[key] = filtered;
      }
    } else if (
      preserveRequiredNullables &&
      value === null &&
      requiredNullableKeys.has(key)
    ) {
      filteredParams[key] = null;
    } else if (
      value != null &&
      (typeof value === 'string' ||
        typeof value === 'number' ||
        typeof value === 'boolean')
    ) {
      filteredParams[key] = value;
    }
  }
  return filteredParams;
}





@Injectable({ providedIn: 'root' })
export class GitReposService {
  private readonly http = inject(HttpClient);
 getApiGitReposUserUsername<TData = GitRepoListResponse>(username: string,
    params?: GetApiGitReposUserUsernameParams, options?: HttpClientBodyOptions): Observable<TData>;
 getApiGitReposUserUsername<TData = GitRepoListResponse>(username: string,
    params?: GetApiGitReposUserUsernameParams, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getApiGitReposUserUsername<TData = GitRepoListResponse>(username: string,
    params?: GetApiGitReposUserUsernameParams, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getApiGitReposUserUsername<TData = GitRepoListResponse>(
    username: string,
    params?: GetApiGitReposUserUsernameParams, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    const filteredParams = filterParams({...params, ...options?.params}, new Set<string>([]));

    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/GitRepos/user/${username}`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
        params: filteredParams,}
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/GitRepos/user/${username}`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
        params: filteredParams,}
    );
    }

    return this.http.get<TData>(
      `/api/GitRepos/user/${username}`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
        params: filteredParams,}
    );
  }
 putApiGitReposRepoIdThumbnail<TData = unknown>(repoId: string,
    putApiGitReposRepoIdThumbnailBody: PutApiGitReposRepoIdThumbnailBody, options?: HttpClientBodyOptions): Observable<TData>;
 putApiGitReposRepoIdThumbnail<TData = unknown>(repoId: string,
    putApiGitReposRepoIdThumbnailBody: PutApiGitReposRepoIdThumbnailBody, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 putApiGitReposRepoIdThumbnail<TData = unknown>(repoId: string,
    putApiGitReposRepoIdThumbnailBody: PutApiGitReposRepoIdThumbnailBody, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  putApiGitReposRepoIdThumbnail<TData = unknown>(
    repoId: string,
    putApiGitReposRepoIdThumbnailBody: PutApiGitReposRepoIdThumbnailBody, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {const formData = new FormData();
if(putApiGitReposRepoIdThumbnailBody.CommitId !== undefined) {
 formData.append(`CommitId`, putApiGitReposRepoIdThumbnailBody.CommitId);
 }
if(putApiGitReposRepoIdThumbnailBody.File !== undefined) {
 formData.append(`File`, putApiGitReposRepoIdThumbnailBody.File);
 }

    if (options?.observe === 'events') {
      return this.http.put<TData>(
      `/api/GitRepos/${repoId}/thumbnail`,
      formData,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.put<TData>(
      `/api/GitRepos/${repoId}/thumbnail`,
      formData,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.put<TData>(
      `/api/GitRepos/${repoId}/thumbnail`,
      formData,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 getApiGitReposRepoId<TData = GitRepoDetailResponse>(repoId: string, options?: HttpClientBodyOptions): Observable<TData>;
 getApiGitReposRepoId<TData = GitRepoDetailResponse>(repoId: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getApiGitReposRepoId<TData = GitRepoDetailResponse>(repoId: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getApiGitReposRepoId<TData = GitRepoDetailResponse>(
    repoId: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/GitRepos/${repoId}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/GitRepos/${repoId}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/GitRepos/${repoId}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 getApiGitReposRepoIdBranchesBranchNameCommits<TData = GitCommitListResponse>(repoId: string,
    branchName: string,
    params?: GetApiGitReposRepoIdBranchesBranchNameCommitsParams, options?: HttpClientBodyOptions): Observable<TData>;
 getApiGitReposRepoIdBranchesBranchNameCommits<TData = GitCommitListResponse>(repoId: string,
    branchName: string,
    params?: GetApiGitReposRepoIdBranchesBranchNameCommitsParams, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getApiGitReposRepoIdBranchesBranchNameCommits<TData = GitCommitListResponse>(repoId: string,
    branchName: string,
    params?: GetApiGitReposRepoIdBranchesBranchNameCommitsParams, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getApiGitReposRepoIdBranchesBranchNameCommits<TData = GitCommitListResponse>(
    repoId: string,
    branchName: string,
    params?: GetApiGitReposRepoIdBranchesBranchNameCommitsParams, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    const filteredParams = filterParams({...params, ...options?.params}, new Set<string>([]));

    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/GitRepos/${repoId}/branches/${branchName}/commits`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
        params: filteredParams,}
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/GitRepos/${repoId}/branches/${branchName}/commits`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
        params: filteredParams,}
    );
    }

    return this.http.get<TData>(
      `/api/GitRepos/${repoId}/branches/${branchName}/commits`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
        params: filteredParams,}
    );
  }
 getApiGitReposCommitsCommitIdDownload<TData = unknown>(commitId: string, options?: HttpClientBodyOptions): Observable<TData>;
 getApiGitReposCommitsCommitIdDownload<TData = unknown>(commitId: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getApiGitReposCommitsCommitIdDownload<TData = unknown>(commitId: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getApiGitReposCommitsCommitIdDownload<TData = unknown>(
    commitId: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/GitRepos/commits/${commitId}/download`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/GitRepos/commits/${commitId}/download`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/GitRepos/commits/${commitId}/download`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 getApiGitReposRepoIdReleases<TData = GitReleaseListResponse>(repoId: string,
    params?: GetApiGitReposRepoIdReleasesParams, options?: HttpClientBodyOptions): Observable<TData>;
 getApiGitReposRepoIdReleases<TData = GitReleaseListResponse>(repoId: string,
    params?: GetApiGitReposRepoIdReleasesParams, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getApiGitReposRepoIdReleases<TData = GitReleaseListResponse>(repoId: string,
    params?: GetApiGitReposRepoIdReleasesParams, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getApiGitReposRepoIdReleases<TData = GitReleaseListResponse>(
    repoId: string,
    params?: GetApiGitReposRepoIdReleasesParams, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    const filteredParams = filterParams({...params, ...options?.params}, new Set<string>([]));

    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/GitRepos/${repoId}/releases`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
        params: filteredParams,}
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/GitRepos/${repoId}/releases`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
        params: filteredParams,}
    );
    }

    return this.http.get<TData>(
      `/api/GitRepos/${repoId}/releases`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
        params: filteredParams,}
    );
  }
 postApiGitReposRepoIdReleases<TData = GitReleaseResponse>(repoId: string,
    postApiGitReposRepoIdReleasesBody: PostApiGitReposRepoIdReleasesBody, options?: HttpClientBodyOptions): Observable<TData>;
 postApiGitReposRepoIdReleases<TData = GitReleaseResponse>(repoId: string,
    postApiGitReposRepoIdReleasesBody: PostApiGitReposRepoIdReleasesBody, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiGitReposRepoIdReleases<TData = GitReleaseResponse>(repoId: string,
    postApiGitReposRepoIdReleasesBody: PostApiGitReposRepoIdReleasesBody, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiGitReposRepoIdReleases<TData = GitReleaseResponse>(
    repoId: string,
    postApiGitReposRepoIdReleasesBody: PostApiGitReposRepoIdReleasesBody, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {const formData = new FormData();
if(postApiGitReposRepoIdReleasesBody.CommitId !== undefined) {
 formData.append(`CommitId`, postApiGitReposRepoIdReleasesBody.CommitId);
 }
if(postApiGitReposRepoIdReleasesBody.TagName !== undefined) {
 formData.append(`TagName`, postApiGitReposRepoIdReleasesBody.TagName);
 }
if(postApiGitReposRepoIdReleasesBody.Name !== undefined) {
 formData.append(`Name`, postApiGitReposRepoIdReleasesBody.Name);
 }
if(postApiGitReposRepoIdReleasesBody.Description !== undefined) {
 formData.append(`Description`, postApiGitReposRepoIdReleasesBody.Description);
 }
if(postApiGitReposRepoIdReleasesBody.Thumbnail !== undefined) {
 formData.append(`Thumbnail`, postApiGitReposRepoIdReleasesBody.Thumbnail);
 }

    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/GitRepos/${repoId}/releases`,
      formData,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/GitRepos/${repoId}/releases`,
      formData,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/GitRepos/${repoId}/releases`,
      formData,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
};

