/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Backend | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient,
  HttpHeaders,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpParams
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  LinkMinecraftRequest,
  ServerLinkDiscordRequest,
  ServerLinkMinecraftRequest,
  ValidateCodeRequest
} from './generated.schemas';




interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
        | HttpParams
      | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: {includeHeaders?: string[]} | boolean;
  readonly timeout?: number;
}

type HttpClientBodyOptions = HttpClientOptions & {
  readonly observe?: 'body';
};

type HttpClientEventOptions = HttpClientOptions & {
  readonly observe: 'events';
};

type HttpClientResponseOptions = HttpClientOptions & {
  readonly observe: 'response';
};

type HttpClientObserveOptions = HttpClientOptions & {
  readonly observe?: 'body' | 'events' | 'response';
};







@Injectable({ providedIn: 'root' })
export class LinkingService {
  private readonly http = inject(HttpClient);
 postApiLinkingMinecraftGenerateCode<TData = unknown>( options?: HttpClientBodyOptions): Observable<TData>;
 postApiLinkingMinecraftGenerateCode<TData = unknown>( options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiLinkingMinecraftGenerateCode<TData = unknown>( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiLinkingMinecraftGenerateCode<TData = unknown>(
     options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/Linking/minecraft/generate-code`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/Linking/minecraft/generate-code`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/Linking/minecraft/generate-code`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 postApiLinkingMinecraftLink<TData = unknown>(linkMinecraftRequest: LinkMinecraftRequest, options?: HttpClientBodyOptions): Observable<TData>;
 postApiLinkingMinecraftLink<TData = unknown>(linkMinecraftRequest: LinkMinecraftRequest, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiLinkingMinecraftLink<TData = unknown>(linkMinecraftRequest: LinkMinecraftRequest, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiLinkingMinecraftLink<TData = unknown>(
    linkMinecraftRequest: LinkMinecraftRequest, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/Linking/minecraft/link`,
      linkMinecraftRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/Linking/minecraft/link`,
      linkMinecraftRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/Linking/minecraft/link`,
      linkMinecraftRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 postApiLinkingMinecraftLinkWithCode<TData = unknown>(serverLinkMinecraftRequest: ServerLinkMinecraftRequest, options?: HttpClientBodyOptions): Observable<TData>;
 postApiLinkingMinecraftLinkWithCode<TData = unknown>(serverLinkMinecraftRequest: ServerLinkMinecraftRequest, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiLinkingMinecraftLinkWithCode<TData = unknown>(serverLinkMinecraftRequest: ServerLinkMinecraftRequest, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiLinkingMinecraftLinkWithCode<TData = unknown>(
    serverLinkMinecraftRequest: ServerLinkMinecraftRequest, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/Linking/minecraft/link-with-code`,
      serverLinkMinecraftRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/Linking/minecraft/link-with-code`,
      serverLinkMinecraftRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/Linking/minecraft/link-with-code`,
      serverLinkMinecraftRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 postApiMinecraftLinkWithCode<TData = unknown>(serverLinkMinecraftRequest: ServerLinkMinecraftRequest, options?: HttpClientBodyOptions): Observable<TData>;
 postApiMinecraftLinkWithCode<TData = unknown>(serverLinkMinecraftRequest: ServerLinkMinecraftRequest, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiMinecraftLinkWithCode<TData = unknown>(serverLinkMinecraftRequest: ServerLinkMinecraftRequest, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiMinecraftLinkWithCode<TData = unknown>(
    serverLinkMinecraftRequest: ServerLinkMinecraftRequest, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/minecraft-link-with-code`,
      serverLinkMinecraftRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/minecraft-link-with-code`,
      serverLinkMinecraftRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/minecraft-link-with-code`,
      serverLinkMinecraftRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 postApiLinkingMinecraftValidateCode<TData = unknown>(validateCodeRequest: ValidateCodeRequest, options?: HttpClientBodyOptions): Observable<TData>;
 postApiLinkingMinecraftValidateCode<TData = unknown>(validateCodeRequest: ValidateCodeRequest, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiLinkingMinecraftValidateCode<TData = unknown>(validateCodeRequest: ValidateCodeRequest, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiLinkingMinecraftValidateCode<TData = unknown>(
    validateCodeRequest: ValidateCodeRequest, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/Linking/minecraft/validate-code`,
      validateCodeRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/Linking/minecraft/validate-code`,
      validateCodeRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/Linking/minecraft/validate-code`,
      validateCodeRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 postApiValidateLinkCode<TData = unknown>(validateCodeRequest: ValidateCodeRequest, options?: HttpClientBodyOptions): Observable<TData>;
 postApiValidateLinkCode<TData = unknown>(validateCodeRequest: ValidateCodeRequest, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiValidateLinkCode<TData = unknown>(validateCodeRequest: ValidateCodeRequest, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiValidateLinkCode<TData = unknown>(
    validateCodeRequest: ValidateCodeRequest, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/validate-link-code`,
      validateCodeRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/validate-link-code`,
      validateCodeRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/validate-link-code`,
      validateCodeRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 postApiLinkingMinecraftUnlink<TData = unknown>( options?: HttpClientBodyOptions): Observable<TData>;
 postApiLinkingMinecraftUnlink<TData = unknown>( options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiLinkingMinecraftUnlink<TData = unknown>( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiLinkingMinecraftUnlink<TData = unknown>(
     options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/Linking/minecraft/unlink`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/Linking/minecraft/unlink`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/Linking/minecraft/unlink`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 getApiLinkingMinecraftStatus<TData = unknown>( options?: HttpClientBodyOptions): Observable<TData>;
 getApiLinkingMinecraftStatus<TData = unknown>( options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getApiLinkingMinecraftStatus<TData = unknown>( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getApiLinkingMinecraftStatus<TData = unknown>(
     options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/Linking/minecraft/status`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/Linking/minecraft/status`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/Linking/minecraft/status`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 postApiLinkingDiscordGenerateCode<TData = unknown>( options?: HttpClientBodyOptions): Observable<TData>;
 postApiLinkingDiscordGenerateCode<TData = unknown>( options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiLinkingDiscordGenerateCode<TData = unknown>( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiLinkingDiscordGenerateCode<TData = unknown>(
     options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/Linking/discord/generate-code`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/Linking/discord/generate-code`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/Linking/discord/generate-code`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 postApiLinkingDiscordLinkWithCode<TData = unknown>(serverLinkDiscordRequest: ServerLinkDiscordRequest, options?: HttpClientBodyOptions): Observable<TData>;
 postApiLinkingDiscordLinkWithCode<TData = unknown>(serverLinkDiscordRequest: ServerLinkDiscordRequest, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiLinkingDiscordLinkWithCode<TData = unknown>(serverLinkDiscordRequest: ServerLinkDiscordRequest, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiLinkingDiscordLinkWithCode<TData = unknown>(
    serverLinkDiscordRequest: ServerLinkDiscordRequest, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/Linking/discord/link-with-code`,
      serverLinkDiscordRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/Linking/discord/link-with-code`,
      serverLinkDiscordRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/Linking/discord/link-with-code`,
      serverLinkDiscordRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 postApiDiscordLinkWithCode<TData = unknown>(serverLinkDiscordRequest: ServerLinkDiscordRequest, options?: HttpClientBodyOptions): Observable<TData>;
 postApiDiscordLinkWithCode<TData = unknown>(serverLinkDiscordRequest: ServerLinkDiscordRequest, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiDiscordLinkWithCode<TData = unknown>(serverLinkDiscordRequest: ServerLinkDiscordRequest, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiDiscordLinkWithCode<TData = unknown>(
    serverLinkDiscordRequest: ServerLinkDiscordRequest, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/discord-link-with-code`,
      serverLinkDiscordRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/discord-link-with-code`,
      serverLinkDiscordRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/discord-link-with-code`,
      serverLinkDiscordRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 postApiLinkingDiscordValidateCode<TData = unknown>(validateCodeRequest: ValidateCodeRequest, options?: HttpClientBodyOptions): Observable<TData>;
 postApiLinkingDiscordValidateCode<TData = unknown>(validateCodeRequest: ValidateCodeRequest, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiLinkingDiscordValidateCode<TData = unknown>(validateCodeRequest: ValidateCodeRequest, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiLinkingDiscordValidateCode<TData = unknown>(
    validateCodeRequest: ValidateCodeRequest, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/Linking/discord/validate-code`,
      validateCodeRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/Linking/discord/validate-code`,
      validateCodeRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/Linking/discord/validate-code`,
      validateCodeRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 postApiValidateDiscordLinkCode<TData = unknown>(validateCodeRequest: ValidateCodeRequest, options?: HttpClientBodyOptions): Observable<TData>;
 postApiValidateDiscordLinkCode<TData = unknown>(validateCodeRequest: ValidateCodeRequest, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiValidateDiscordLinkCode<TData = unknown>(validateCodeRequest: ValidateCodeRequest, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiValidateDiscordLinkCode<TData = unknown>(
    validateCodeRequest: ValidateCodeRequest, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/validate-discord-link-code`,
      validateCodeRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/validate-discord-link-code`,
      validateCodeRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/validate-discord-link-code`,
      validateCodeRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 postApiLinkingDiscordUnlinkDiscordId<TData = unknown>(discordId: string, options?: HttpClientBodyOptions): Observable<TData>;
 postApiLinkingDiscordUnlinkDiscordId<TData = unknown>(discordId: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiLinkingDiscordUnlinkDiscordId<TData = unknown>(discordId: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiLinkingDiscordUnlinkDiscordId<TData = unknown>(
    discordId: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/Linking/discord/unlink/${discordId}`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/Linking/discord/unlink/${discordId}`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/Linking/discord/unlink/${discordId}`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 postApiUnlinkDiscordDiscordId<TData = unknown>(discordId: string, options?: HttpClientBodyOptions): Observable<TData>;
 postApiUnlinkDiscordDiscordId<TData = unknown>(discordId: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiUnlinkDiscordDiscordId<TData = unknown>(discordId: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiUnlinkDiscordDiscordId<TData = unknown>(
    discordId: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/unlink-discord/${discordId}`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/unlink-discord/${discordId}`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/unlink-discord/${discordId}`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 postApiLinkingDiscordUnlink<TData = unknown>( options?: HttpClientBodyOptions): Observable<TData>;
 postApiLinkingDiscordUnlink<TData = unknown>( options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiLinkingDiscordUnlink<TData = unknown>( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiLinkingDiscordUnlink<TData = unknown>(
     options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/Linking/discord/unlink`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/Linking/discord/unlink`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/Linking/discord/unlink`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 getApiLinkingDiscordStatus<TData = unknown>( options?: HttpClientBodyOptions): Observable<TData>;
 getApiLinkingDiscordStatus<TData = unknown>( options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getApiLinkingDiscordStatus<TData = unknown>( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getApiLinkingDiscordStatus<TData = unknown>(
     options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/Linking/discord/status`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/Linking/discord/status`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/Linking/discord/status`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 getApiLinkingDiscordStatusDiscordId<TData = unknown>(discordId: string, options?: HttpClientBodyOptions): Observable<TData>;
 getApiLinkingDiscordStatusDiscordId<TData = unknown>(discordId: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getApiLinkingDiscordStatusDiscordId<TData = unknown>(discordId: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getApiLinkingDiscordStatusDiscordId<TData = unknown>(
    discordId: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/Linking/discord/status/${discordId}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/Linking/discord/status/${discordId}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/Linking/discord/status/${discordId}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
};

