/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Backend | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient,
  HttpHeaders
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpParams,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  ModListItemResponse,
  PostApiModsBody,
  PutApiModsIdBody
} from './generated.schemas';




interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
        | HttpParams
      | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: {includeHeaders?: string[]} | boolean;
}





@Injectable({ providedIn: 'root' })
export class ModsService {
  private readonly http = inject(HttpClient);
 getApiMods<TData = ModListItemResponse[]>( options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 getApiMods<TData = ModListItemResponse[]>( options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 getApiMods<TData = ModListItemResponse[]>( options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  getApiMods<TData = ModListItemResponse[]>(
     options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/Mods`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/Mods`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/Mods`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 postApiMods<TData = ModListItemResponse>(postApiModsBody: PostApiModsBody, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiMods<TData = ModListItemResponse>(postApiModsBody: PostApiModsBody, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiMods<TData = ModListItemResponse>(postApiModsBody: PostApiModsBody, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiMods<TData = ModListItemResponse>(
    postApiModsBody: PostApiModsBody, options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {const formData = new FormData();
if(postApiModsBody.Title !== undefined) {
 formData.append(`Title`, postApiModsBody.Title);
 }
if(postApiModsBody.Description !== undefined) {
 formData.append(`Description`, postApiModsBody.Description);
 }
if(postApiModsBody.ReleaseType !== undefined) {
 formData.append(`ReleaseType`, postApiModsBody.ReleaseType);
 }
if(postApiModsBody.GameVersion !== undefined) {
 formData.append(`GameVersion`, postApiModsBody.GameVersion);
 }
if(postApiModsBody.Platform !== undefined) {
 formData.append(`Platform`, postApiModsBody.Platform);
 }
if(postApiModsBody.File !== undefined) {
 formData.append(`File`, postApiModsBody.File);
 }
if(postApiModsBody.Image !== undefined) {
 formData.append(`Image`, postApiModsBody.Image);
 }

    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/Mods`,
      formData,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/Mods`,
      formData,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/Mods`,
      formData,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 getApiModsId<TData = ModListItemResponse>(id: number, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 getApiModsId<TData = ModListItemResponse>(id: number, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 getApiModsId<TData = ModListItemResponse>(id: number, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  getApiModsId<TData = ModListItemResponse>(
    id: number, options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/Mods/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/Mods/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/Mods/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 putApiModsId<TData = ModListItemResponse>(id: number,
    putApiModsIdBody: PutApiModsIdBody, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 putApiModsId<TData = ModListItemResponse>(id: number,
    putApiModsIdBody: PutApiModsIdBody, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 putApiModsId<TData = ModListItemResponse>(id: number,
    putApiModsIdBody: PutApiModsIdBody, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  putApiModsId<TData = ModListItemResponse>(
    id: number,
    putApiModsIdBody: PutApiModsIdBody, options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {const formData = new FormData();
if(putApiModsIdBody.Title !== undefined) {
 formData.append(`Title`, putApiModsIdBody.Title);
 }
if(putApiModsIdBody.Description !== undefined) {
 formData.append(`Description`, putApiModsIdBody.Description);
 }
if(putApiModsIdBody.ReleaseType !== undefined) {
 formData.append(`ReleaseType`, putApiModsIdBody.ReleaseType);
 }
if(putApiModsIdBody.GameVersion !== undefined) {
 formData.append(`GameVersion`, putApiModsIdBody.GameVersion);
 }
if(putApiModsIdBody.Platform !== undefined) {
 formData.append(`Platform`, putApiModsIdBody.Platform);
 }
if(putApiModsIdBody.File !== undefined) {
 formData.append(`File`, putApiModsIdBody.File);
 }
if(putApiModsIdBody.Image !== undefined) {
 formData.append(`Image`, putApiModsIdBody.Image);
 }

    if (options?.observe === 'events') {
      return this.http.put<TData>(
      `/api/Mods/${id}`,
      formData,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.put<TData>(
      `/api/Mods/${id}`,
      formData,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.put<TData>(
      `/api/Mods/${id}`,
      formData,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 deleteApiModsId<TData = unknown>(id: number, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 deleteApiModsId<TData = unknown>(id: number, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 deleteApiModsId<TData = unknown>(id: number, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  deleteApiModsId<TData = unknown>(
    id: number, options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.delete<TData>(
      `/api/Mods/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.delete<TData>(
      `/api/Mods/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.delete<TData>(
      `/api/Mods/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 getApiModsIdDownload<TData = unknown>(id: number, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 getApiModsIdDownload<TData = unknown>(id: number, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 getApiModsIdDownload<TData = unknown>(id: number, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  getApiModsIdDownload<TData = unknown>(
    id: number, options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/Mods/${id}/download`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/Mods/${id}/download`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/Mods/${id}/download`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
}

