/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Backend | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient,
  HttpHeaders,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpParams
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  ConfirmPasswordResetRequest,
  RequestPasswordResetRequest
} from './generated.schemas';




interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
        | HttpParams
      | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: {includeHeaders?: string[]} | boolean;
  readonly timeout?: number;
}

type HttpClientBodyOptions = HttpClientOptions & {
  readonly observe?: 'body';
};

type HttpClientEventOptions = HttpClientOptions & {
  readonly observe: 'events';
};

type HttpClientResponseOptions = HttpClientOptions & {
  readonly observe: 'response';
};

type HttpClientObserveOptions = HttpClientOptions & {
  readonly observe?: 'body' | 'events' | 'response';
};







@Injectable({ providedIn: 'root' })
export class PasswordResetService {
  private readonly http = inject(HttpClient);
 postApiPasswordResetRequest<TData = unknown>(requestPasswordResetRequest: RequestPasswordResetRequest, options?: HttpClientBodyOptions): Observable<TData>;
 postApiPasswordResetRequest<TData = unknown>(requestPasswordResetRequest: RequestPasswordResetRequest, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiPasswordResetRequest<TData = unknown>(requestPasswordResetRequest: RequestPasswordResetRequest, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiPasswordResetRequest<TData = unknown>(
    requestPasswordResetRequest: RequestPasswordResetRequest, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/PasswordReset/request`,
      requestPasswordResetRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/PasswordReset/request`,
      requestPasswordResetRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/PasswordReset/request`,
      requestPasswordResetRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 postApiPasswordResetConfirm<TData = unknown>(confirmPasswordResetRequest: ConfirmPasswordResetRequest, options?: HttpClientBodyOptions): Observable<TData>;
 postApiPasswordResetConfirm<TData = unknown>(confirmPasswordResetRequest: ConfirmPasswordResetRequest, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiPasswordResetConfirm<TData = unknown>(confirmPasswordResetRequest: ConfirmPasswordResetRequest, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiPasswordResetConfirm<TData = unknown>(
    confirmPasswordResetRequest: ConfirmPasswordResetRequest, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/PasswordReset/confirm`,
      confirmPasswordResetRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/PasswordReset/confirm`,
      confirmPasswordResetRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/PasswordReset/confirm`,
      confirmPasswordResetRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
};

