/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Backend | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient,
  HttpHeaders,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpParams
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  ReportSchematicRequest,
  ReportUserRequest
} from './generated.schemas';




interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
        | HttpParams
      | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: {includeHeaders?: string[]} | boolean;
  readonly timeout?: number;
}

type HttpClientBodyOptions = HttpClientOptions & {
  readonly observe?: 'body';
};

type HttpClientEventOptions = HttpClientOptions & {
  readonly observe: 'events';
};

type HttpClientResponseOptions = HttpClientOptions & {
  readonly observe: 'response';
};

type HttpClientObserveOptions = HttpClientOptions & {
  readonly observe?: 'body' | 'events' | 'response';
};







@Injectable({ providedIn: 'root' })
export class ReportsService {
  private readonly http = inject(HttpClient);
 postApiReportsUser<TData = unknown>(reportUserRequest: ReportUserRequest, options?: HttpClientBodyOptions): Observable<TData>;
 postApiReportsUser<TData = unknown>(reportUserRequest: ReportUserRequest, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiReportsUser<TData = unknown>(reportUserRequest: ReportUserRequest, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiReportsUser<TData = unknown>(
    reportUserRequest: ReportUserRequest, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/Reports/user`,
      reportUserRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/Reports/user`,
      reportUserRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/Reports/user`,
      reportUserRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 postApiReportsSchematic<TData = unknown>(reportSchematicRequest: ReportSchematicRequest, options?: HttpClientBodyOptions): Observable<TData>;
 postApiReportsSchematic<TData = unknown>(reportSchematicRequest: ReportSchematicRequest, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiReportsSchematic<TData = unknown>(reportSchematicRequest: ReportSchematicRequest, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiReportsSchematic<TData = unknown>(
    reportSchematicRequest: ReportSchematicRequest, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/Reports/schematic`,
      reportSchematicRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/Reports/schematic`,
      reportSchematicRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/Reports/schematic`,
      reportSchematicRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
};

