/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Backend | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient,
  HttpHeaders,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpParams
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  RegenerateSaveKeyResponse,
  SaveListItemResponse,
  SaveQuotaResponse,
  VerifyPasswordRequest
} from './generated.schemas';




interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
        | HttpParams
      | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: {includeHeaders?: string[]} | boolean;
  readonly timeout?: number;
}

type HttpClientBodyOptions = HttpClientOptions & {
  readonly observe?: 'body';
};

type HttpClientEventOptions = HttpClientOptions & {
  readonly observe: 'events';
};

type HttpClientResponseOptions = HttpClientOptions & {
  readonly observe: 'response';
};

type HttpClientObserveOptions = HttpClientOptions & {
  readonly observe?: 'body' | 'events' | 'response';
};







@Injectable({ providedIn: 'root' })
export class SaveManagerService {
  private readonly http = inject(HttpClient);
 getApiSaveManager<TData = SaveListItemResponse[]>( options?: HttpClientBodyOptions): Observable<TData>;
 getApiSaveManager<TData = SaveListItemResponse[]>( options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getApiSaveManager<TData = SaveListItemResponse[]>( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getApiSaveManager<TData = SaveListItemResponse[]>(
     options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/SaveManager`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/SaveManager`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/SaveManager`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 getApiSaveManagerQuota<TData = SaveQuotaResponse>( options?: HttpClientBodyOptions): Observable<TData>;
 getApiSaveManagerQuota<TData = SaveQuotaResponse>( options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getApiSaveManagerQuota<TData = SaveQuotaResponse>( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getApiSaveManagerQuota<TData = SaveQuotaResponse>(
     options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/SaveManager/quota`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/SaveManager/quota`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/SaveManager/quota`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 getApiSaveManagerIdDownload<TData = unknown>(id: string, options?: HttpClientBodyOptions): Observable<TData>;
 getApiSaveManagerIdDownload<TData = unknown>(id: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getApiSaveManagerIdDownload<TData = unknown>(id: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getApiSaveManagerIdDownload<TData = unknown>(
    id: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/SaveManager/${id}/download`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/SaveManager/${id}/download`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/SaveManager/${id}/download`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 deleteApiSaveManagerId<TData = unknown>(id: string, options?: HttpClientBodyOptions): Observable<TData>;
 deleteApiSaveManagerId<TData = unknown>(id: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 deleteApiSaveManagerId<TData = unknown>(id: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  deleteApiSaveManagerId<TData = unknown>(
    id: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.delete<TData>(
      `/api/SaveManager/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.delete<TData>(
      `/api/SaveManager/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.delete<TData>(
      `/api/SaveManager/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 postApiSaveManagerVerifyPassword<TData = unknown>(verifyPasswordRequest: VerifyPasswordRequest, options?: HttpClientBodyOptions): Observable<TData>;
 postApiSaveManagerVerifyPassword<TData = unknown>(verifyPasswordRequest: VerifyPasswordRequest, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiSaveManagerVerifyPassword<TData = unknown>(verifyPasswordRequest: VerifyPasswordRequest, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiSaveManagerVerifyPassword<TData = unknown>(
    verifyPasswordRequest: VerifyPasswordRequest, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/SaveManager/verify-password`,
      verifyPasswordRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/SaveManager/verify-password`,
      verifyPasswordRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/SaveManager/verify-password`,
      verifyPasswordRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 postApiSaveManagerRegenerateKey<TData = RegenerateSaveKeyResponse>( options?: HttpClientBodyOptions): Observable<TData>;
 postApiSaveManagerRegenerateKey<TData = RegenerateSaveKeyResponse>( options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiSaveManagerRegenerateKey<TData = RegenerateSaveKeyResponse>( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiSaveManagerRegenerateKey<TData = RegenerateSaveKeyResponse>(
     options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/SaveManager/regenerate-key`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/SaveManager/regenerate-key`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/SaveManager/regenerate-key`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 getApiSaveManagerFlowFlowId<TData = unknown>(flowId: string, options?: HttpClientBodyOptions): Observable<TData>;
 getApiSaveManagerFlowFlowId<TData = unknown>(flowId: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getApiSaveManagerFlowFlowId<TData = unknown>(flowId: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getApiSaveManagerFlowFlowId<TData = unknown>(
    flowId: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/SaveManager/flow/${flowId}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/SaveManager/flow/${flowId}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/SaveManager/flow/${flowId}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 postApiSaveManagerFlowFlowIdApprove<TData = unknown>(flowId: string, options?: HttpClientBodyOptions): Observable<TData>;
 postApiSaveManagerFlowFlowIdApprove<TData = unknown>(flowId: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiSaveManagerFlowFlowIdApprove<TData = unknown>(flowId: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiSaveManagerFlowFlowIdApprove<TData = unknown>(
    flowId: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/SaveManager/flow/${flowId}/approve`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/SaveManager/flow/${flowId}/approve`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/SaveManager/flow/${flowId}/approve`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 postApiSaveManagerFlowFlowIdCancel<TData = unknown>(flowId: string, options?: HttpClientBodyOptions): Observable<TData>;
 postApiSaveManagerFlowFlowIdCancel<TData = unknown>(flowId: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiSaveManagerFlowFlowIdCancel<TData = unknown>(flowId: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiSaveManagerFlowFlowIdCancel<TData = unknown>(
    flowId: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/SaveManager/flow/${flowId}/cancel`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/SaveManager/flow/${flowId}/cancel`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/SaveManager/flow/${flowId}/cancel`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
};

