/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Backend | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient,
  HttpHeaders,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpParams
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  AllowedTagResponse,
  AllowedVersionResponse,
  AuthorSearchResultResponse,
  GetApiSchematicsParams,
  GetApiSchematicsSearchAuthorsParams,
  GetApiSchematicsSearchNamesParams,
  GetApiSchematicsSearchTagsParams,
  GetApiSchematicsSearchUsersParams,
  GetApiSchematicsUserUsernameSchematicsParams,
  LikeResponse,
  PostApiSchematicsBody,
  PutApiSchematicsIdBody,
  SchematicDetailResponse,
  SchematicListResponse,
  UserContentResponse
} from './generated.schemas';




interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
        | HttpParams
      | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: {includeHeaders?: string[]} | boolean;
  readonly timeout?: number;
}

type HttpClientBodyOptions = HttpClientOptions & {
  readonly observe?: 'body';
};

type HttpClientEventOptions = HttpClientOptions & {
  readonly observe: 'events';
};

type HttpClientResponseOptions = HttpClientOptions & {
  readonly observe: 'response';
};

type HttpClientObserveOptions = HttpClientOptions & {
  readonly observe?: 'body' | 'events' | 'response';
};

type AngularHttpParamValue = string | number | boolean | Array<string | number | boolean>;
type AngularHttpParamValueWithNullable = AngularHttpParamValue | null;

function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys?: ReadonlySet<string>,
  preserveRequiredNullables?: false,
  passthroughKeys?: undefined,
): Record<string, AngularHttpParamValue>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> | undefined,
  preserveRequiredNullables: true,
  passthroughKeys?: undefined,
): Record<string, AngularHttpParamValueWithNullable>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> | undefined,
  preserveRequiredNullables: boolean | undefined,
  passthroughKeys: ReadonlySet<string>,
): Record<string, unknown>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> = new Set(),
  preserveRequiredNullables = false,
  passthroughKeys: ReadonlySet<string> = new Set(),
): Record<string, unknown> {
  const filteredParams: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(params)) {
    if (passthroughKeys.has(key)) {
      if (value !== undefined) {
        filteredParams[key] = value;
      }
      continue;
    }
    if (Array.isArray(value)) {
      const filtered = value.filter(
        (item) =>
          item != null &&
          (typeof item === 'string' ||
            typeof item === 'number' ||
            typeof item === 'boolean'),
      ) as Array<string | number | boolean>;
      if (filtered.length) {
        filteredParams[key] = filtered;
      }
    } else if (
      preserveRequiredNullables &&
      value === null &&
      requiredNullableKeys.has(key)
    ) {
      filteredParams[key] = null;
    } else if (
      value != null &&
      (typeof value === 'string' ||
        typeof value === 'number' ||
        typeof value === 'boolean')
    ) {
      filteredParams[key] = value;
    }
  }
  return filteredParams;
}





@Injectable({ providedIn: 'root' })
export class SchematicsService {
  private readonly http = inject(HttpClient);
 getApiSchematics<TData = SchematicListResponse>(params?: GetApiSchematicsParams, options?: HttpClientBodyOptions): Observable<TData>;
 getApiSchematics<TData = SchematicListResponse>(params?: GetApiSchematicsParams, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getApiSchematics<TData = SchematicListResponse>(params?: GetApiSchematicsParams, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getApiSchematics<TData = SchematicListResponse>(
    params?: GetApiSchematicsParams, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    const filteredParams = filterParams({...params, ...options?.params}, new Set<string>([]));

    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/Schematics`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
        params: filteredParams,}
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/Schematics`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
        params: filteredParams,}
    );
    }

    return this.http.get<TData>(
      `/api/Schematics`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
        params: filteredParams,}
    );
  }
 postApiSchematics<TData = SchematicDetailResponse>(postApiSchematicsBody: PostApiSchematicsBody, options?: HttpClientBodyOptions): Observable<TData>;
 postApiSchematics<TData = SchematicDetailResponse>(postApiSchematicsBody: PostApiSchematicsBody, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiSchematics<TData = SchematicDetailResponse>(postApiSchematicsBody: PostApiSchematicsBody, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiSchematics<TData = SchematicDetailResponse>(
    postApiSchematicsBody: PostApiSchematicsBody, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {const formData = new FormData();
if(postApiSchematicsBody.Name !== undefined) {
 formData.append(`Name`, postApiSchematicsBody.Name);
 }
if(postApiSchematicsBody.Description !== undefined) {
 formData.append(`Description`, postApiSchematicsBody.Description);
 }
if(postApiSchematicsBody.AuthorName !== undefined) {
 formData.append(`AuthorName`, postApiSchematicsBody.AuthorName);
 }
if(postApiSchematicsBody.SchematicsPictureFiles !== undefined) {
 postApiSchematicsBody.SchematicsPictureFiles.forEach(value => formData.append(`SchematicsPictureFiles`, value));
 }
if(postApiSchematicsBody.LitematicFiles !== undefined) {
 postApiSchematicsBody.LitematicFiles.forEach(value => formData.append(`LitematicFiles`, value));
 }
if(postApiSchematicsBody.DownloadLinkMediaFire !== undefined) {
 formData.append(`DownloadLinkMediaFire`, postApiSchematicsBody.DownloadLinkMediaFire);
 }
if(postApiSchematicsBody.YoutubeLink !== undefined) {
 formData.append(`YoutubeLink`, postApiSchematicsBody.YoutubeLink);
 }
if(postApiSchematicsBody.Tags !== undefined) {
 formData.append(`Tags`, postApiSchematicsBody.Tags);
 }
if(postApiSchematicsBody.Versions !== undefined) {
 formData.append(`Versions`, postApiSchematicsBody.Versions);
 }
if(postApiSchematicsBody.CoverImageIndex !== undefined) {
 formData.append(`CoverImageIndex`, postApiSchematicsBody.CoverImageIndex.toString())
 }
if(postApiSchematicsBody.SchematicType !== undefined) {
 formData.append(`SchematicType`, postApiSchematicsBody.SchematicType);
 }
if(postApiSchematicsBody.Visibility !== undefined) {
 formData.append(`Visibility`, postApiSchematicsBody.Visibility);
 }
if(postApiSchematicsBody.IsModule !== undefined) {
 formData.append(`IsModule`, postApiSchematicsBody.IsModule.toString())
 }

    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/Schematics`,
      formData,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/Schematics`,
      formData,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/Schematics`,
      formData,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 getApiSchematicsId<TData = SchematicDetailResponse>(id: string, options?: HttpClientBodyOptions): Observable<TData>;
 getApiSchematicsId<TData = SchematicDetailResponse>(id: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getApiSchematicsId<TData = SchematicDetailResponse>(id: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getApiSchematicsId<TData = SchematicDetailResponse>(
    id: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/Schematics/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/Schematics/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/Schematics/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 putApiSchematicsId<TData = unknown>(id: string,
    putApiSchematicsIdBody: PutApiSchematicsIdBody, options?: HttpClientBodyOptions): Observable<TData>;
 putApiSchematicsId<TData = unknown>(id: string,
    putApiSchematicsIdBody: PutApiSchematicsIdBody, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 putApiSchematicsId<TData = unknown>(id: string,
    putApiSchematicsIdBody: PutApiSchematicsIdBody, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  putApiSchematicsId<TData = unknown>(
    id: string,
    putApiSchematicsIdBody: PutApiSchematicsIdBody, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {const formData = new FormData();
if(putApiSchematicsIdBody.Name !== undefined) {
 formData.append(`Name`, putApiSchematicsIdBody.Name);
 }
if(putApiSchematicsIdBody.Description !== undefined) {
 formData.append(`Description`, putApiSchematicsIdBody.Description);
 }
if(putApiSchematicsIdBody.AuthorName !== undefined) {
 formData.append(`AuthorName`, putApiSchematicsIdBody.AuthorName);
 }
if(putApiSchematicsIdBody.NewPictureFiles !== undefined) {
 putApiSchematicsIdBody.NewPictureFiles.forEach(value => formData.append(`NewPictureFiles`, value));
 }
if(putApiSchematicsIdBody.NewLitematicFiles !== undefined) {
 putApiSchematicsIdBody.NewLitematicFiles.forEach(value => formData.append(`NewLitematicFiles`, value));
 }
if(putApiSchematicsIdBody.RemovePictureIds !== undefined) {
 formData.append(`RemovePictureIds`, putApiSchematicsIdBody.RemovePictureIds);
 }
if(putApiSchematicsIdBody.RemoveFileIds !== undefined) {
 formData.append(`RemoveFileIds`, putApiSchematicsIdBody.RemoveFileIds);
 }
if(putApiSchematicsIdBody.DownloadLinkMediaFire !== undefined) {
 formData.append(`DownloadLinkMediaFire`, putApiSchematicsIdBody.DownloadLinkMediaFire);
 }
if(putApiSchematicsIdBody.YoutubeLink !== undefined) {
 formData.append(`YoutubeLink`, putApiSchematicsIdBody.YoutubeLink);
 }
if(putApiSchematicsIdBody.Tags !== undefined) {
 formData.append(`Tags`, putApiSchematicsIdBody.Tags);
 }
if(putApiSchematicsIdBody.Versions !== undefined) {
 formData.append(`Versions`, putApiSchematicsIdBody.Versions);
 }
if(putApiSchematicsIdBody.CoverImageIndex !== undefined) {
 formData.append(`CoverImageIndex`, putApiSchematicsIdBody.CoverImageIndex.toString())
 }
if(putApiSchematicsIdBody.PictureOrder !== undefined) {
 formData.append(`PictureOrder`, putApiSchematicsIdBody.PictureOrder);
 }
if(putApiSchematicsIdBody.FileOrder !== undefined) {
 formData.append(`FileOrder`, putApiSchematicsIdBody.FileOrder);
 }
if(putApiSchematicsIdBody.SchematicType !== undefined) {
 formData.append(`SchematicType`, putApiSchematicsIdBody.SchematicType);
 }
if(putApiSchematicsIdBody.Visibility !== undefined) {
 formData.append(`Visibility`, putApiSchematicsIdBody.Visibility);
 }

    if (options?.observe === 'events') {
      return this.http.put<TData>(
      `/api/Schematics/${id}`,
      formData,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.put<TData>(
      `/api/Schematics/${id}`,
      formData,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.put<TData>(
      `/api/Schematics/${id}`,
      formData,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 deleteApiSchematicsId<TData = unknown>(id: string, options?: HttpClientBodyOptions): Observable<TData>;
 deleteApiSchematicsId<TData = unknown>(id: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 deleteApiSchematicsId<TData = unknown>(id: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  deleteApiSchematicsId<TData = unknown>(
    id: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.delete<TData>(
      `/api/Schematics/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.delete<TData>(
      `/api/Schematics/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.delete<TData>(
      `/api/Schematics/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 postApiSchematicsIdLike<TData = LikeResponse>(id: string, options?: HttpClientBodyOptions): Observable<TData>;
 postApiSchematicsIdLike<TData = LikeResponse>(id: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiSchematicsIdLike<TData = LikeResponse>(id: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiSchematicsIdLike<TData = LikeResponse>(
    id: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/Schematics/${id}/like`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/Schematics/${id}/like`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/Schematics/${id}/like`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 postApiSchematicsIdFork<TData = unknown>(id: string, options?: HttpClientBodyOptions): Observable<TData>;
 postApiSchematicsIdFork<TData = unknown>(id: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiSchematicsIdFork<TData = unknown>(id: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiSchematicsIdFork<TData = unknown>(
    id: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/Schematics/${id}/fork`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/Schematics/${id}/fork`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/Schematics/${id}/fork`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 getApiSchematicsIdDownload<TData = unknown>(id: string, options?: HttpClientBodyOptions): Observable<TData>;
 getApiSchematicsIdDownload<TData = unknown>(id: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getApiSchematicsIdDownload<TData = unknown>(id: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getApiSchematicsIdDownload<TData = unknown>(
    id: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/Schematics/${id}/download`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/Schematics/${id}/download`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/Schematics/${id}/download`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 getApiSchematicsIdDownloadFileId<TData = unknown>(id: string,
    fileId: number, options?: HttpClientBodyOptions): Observable<TData>;
 getApiSchematicsIdDownloadFileId<TData = unknown>(id: string,
    fileId: number, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getApiSchematicsIdDownloadFileId<TData = unknown>(id: string,
    fileId: number, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getApiSchematicsIdDownloadFileId<TData = unknown>(
    id: string,
    fileId: number, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/Schematics/${id}/download/${fileId}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/Schematics/${id}/download/${fileId}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/Schematics/${id}/download/${fileId}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 getApiSchematicsSearchNames<TData = string[]>(params?: GetApiSchematicsSearchNamesParams, options?: HttpClientBodyOptions): Observable<TData>;
 getApiSchematicsSearchNames<TData = string[]>(params?: GetApiSchematicsSearchNamesParams, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getApiSchematicsSearchNames<TData = string[]>(params?: GetApiSchematicsSearchNamesParams, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getApiSchematicsSearchNames<TData = string[]>(
    params?: GetApiSchematicsSearchNamesParams, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    const filteredParams = filterParams({...params, ...options?.params}, new Set<string>([]));

    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/Schematics/search/names`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
        params: filteredParams,}
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/Schematics/search/names`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
        params: filteredParams,}
    );
    }

    return this.http.get<TData>(
      `/api/Schematics/search/names`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
        params: filteredParams,}
    );
  }
 getApiSchematicsSearchUsers<TData = string[]>(params?: GetApiSchematicsSearchUsersParams, options?: HttpClientBodyOptions): Observable<TData>;
 getApiSchematicsSearchUsers<TData = string[]>(params?: GetApiSchematicsSearchUsersParams, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getApiSchematicsSearchUsers<TData = string[]>(params?: GetApiSchematicsSearchUsersParams, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getApiSchematicsSearchUsers<TData = string[]>(
    params?: GetApiSchematicsSearchUsersParams, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    const filteredParams = filterParams({...params, ...options?.params}, new Set<string>([]));

    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/Schematics/search/users`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
        params: filteredParams,}
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/Schematics/search/users`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
        params: filteredParams,}
    );
    }

    return this.http.get<TData>(
      `/api/Schematics/search/users`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
        params: filteredParams,}
    );
  }
 getApiSchematicsSearchTags<TData = string[]>(params?: GetApiSchematicsSearchTagsParams, options?: HttpClientBodyOptions): Observable<TData>;
 getApiSchematicsSearchTags<TData = string[]>(params?: GetApiSchematicsSearchTagsParams, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getApiSchematicsSearchTags<TData = string[]>(params?: GetApiSchematicsSearchTagsParams, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getApiSchematicsSearchTags<TData = string[]>(
    params?: GetApiSchematicsSearchTagsParams, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    const filteredParams = filterParams({...params, ...options?.params}, new Set<string>([]));

    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/Schematics/search/tags`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
        params: filteredParams,}
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/Schematics/search/tags`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
        params: filteredParams,}
    );
    }

    return this.http.get<TData>(
      `/api/Schematics/search/tags`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
        params: filteredParams,}
    );
  }
 getApiSchematicsTags<TData = AllowedTagResponse[]>( options?: HttpClientBodyOptions): Observable<TData>;
 getApiSchematicsTags<TData = AllowedTagResponse[]>( options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getApiSchematicsTags<TData = AllowedTagResponse[]>( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getApiSchematicsTags<TData = AllowedTagResponse[]>(
     options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/Schematics/tags`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/Schematics/tags`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/Schematics/tags`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 getApiSchematicsVersions<TData = AllowedVersionResponse[]>( options?: HttpClientBodyOptions): Observable<TData>;
 getApiSchematicsVersions<TData = AllowedVersionResponse[]>( options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getApiSchematicsVersions<TData = AllowedVersionResponse[]>( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getApiSchematicsVersions<TData = AllowedVersionResponse[]>(
     options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/Schematics/versions`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/Schematics/versions`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/Schematics/versions`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 getApiSchematicsSearchAuthors<TData = AuthorSearchResultResponse[]>(params?: GetApiSchematicsSearchAuthorsParams, options?: HttpClientBodyOptions): Observable<TData>;
 getApiSchematicsSearchAuthors<TData = AuthorSearchResultResponse[]>(params?: GetApiSchematicsSearchAuthorsParams, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getApiSchematicsSearchAuthors<TData = AuthorSearchResultResponse[]>(params?: GetApiSchematicsSearchAuthorsParams, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getApiSchematicsSearchAuthors<TData = AuthorSearchResultResponse[]>(
    params?: GetApiSchematicsSearchAuthorsParams, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    const filteredParams = filterParams({...params, ...options?.params}, new Set<string>([]));

    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/Schematics/search/authors`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
        params: filteredParams,}
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/Schematics/search/authors`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
        params: filteredParams,}
    );
    }

    return this.http.get<TData>(
      `/api/Schematics/search/authors`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
        params: filteredParams,}
    );
  }
 getApiSchematicsUserUsernameSchematics<TData = SchematicListResponse>(username: string,
    params?: GetApiSchematicsUserUsernameSchematicsParams, options?: HttpClientBodyOptions): Observable<TData>;
 getApiSchematicsUserUsernameSchematics<TData = SchematicListResponse>(username: string,
    params?: GetApiSchematicsUserUsernameSchematicsParams, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getApiSchematicsUserUsernameSchematics<TData = SchematicListResponse>(username: string,
    params?: GetApiSchematicsUserUsernameSchematicsParams, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getApiSchematicsUserUsernameSchematics<TData = SchematicListResponse>(
    username: string,
    params?: GetApiSchematicsUserUsernameSchematicsParams, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    const filteredParams = filterParams({...params, ...options?.params}, new Set<string>([]));

    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/Schematics/user/${username}/schematics`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
        params: filteredParams,}
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/Schematics/user/${username}/schematics`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
        params: filteredParams,}
    );
    }

    return this.http.get<TData>(
      `/api/Schematics/user/${username}/schematics`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
        params: filteredParams,}
    );
  }
 getApiSchematicsUserUsernameContent<TData = UserContentResponse>(username: string, options?: HttpClientBodyOptions): Observable<TData>;
 getApiSchematicsUserUsernameContent<TData = UserContentResponse>(username: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getApiSchematicsUserUsernameContent<TData = UserContentResponse>(username: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getApiSchematicsUserUsernameContent<TData = UserContentResponse>(
    username: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/Schematics/user/${username}/content`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/Schematics/user/${username}/content`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/Schematics/user/${username}/content`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
};

