/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Backend | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient,
  HttpHeaders
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpParams,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  AddSecurityKeyRequest,
  AuthenticatorAssertionRawResponse,
  AuthenticatorAttestationRawResponse,
  JsonElement,
  LoginResponse,
  PostApiSecurityKeysLoginParams,
  PostApiSecurityKeysRegisterParams,
  SecurityKeyResponse
} from './generated.schemas';




interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
        | HttpParams
      | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: {includeHeaders?: string[]} | boolean;
}

function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: Set<string> = new Set(),
): Record<string, string | number | boolean | Array<string | number | boolean>> {
  const filteredParams: Record<string, string | number | boolean | null | Array<string | number | boolean>> = {};
  for (const [key, value] of Object.entries(params)) {
    if (Array.isArray(value)) {
      const filtered = value.filter(
        (item) =>
          item != null &&
          (typeof item === 'string' ||
            typeof item === 'number' ||
            typeof item === 'boolean'),
      ) as Array<string | number | boolean>;
      if (filtered.length) {
        filteredParams[key] = filtered;
      }
    } else if (value === null && requiredNullableKeys.has(key)) {
      filteredParams[key] = value;
    } else if (
      value != null &&
      (typeof value === 'string' ||
        typeof value === 'number' ||
        typeof value === 'boolean')
    ) {
      filteredParams[key] = value as string | number | boolean;
    }
  }
  return filteredParams as Record<string, string | number | boolean | Array<string | number | boolean>>;
}



@Injectable({ providedIn: 'root' })
export class SecurityKeysService {
  private readonly http = inject(HttpClient);
 getApiSecurityKeys<TData = SecurityKeyResponse[]>( options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 getApiSecurityKeys<TData = SecurityKeyResponse[]>( options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 getApiSecurityKeys<TData = SecurityKeyResponse[]>( options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  getApiSecurityKeys<TData = SecurityKeyResponse[]>(
     options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/SecurityKeys`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/SecurityKeys`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/SecurityKeys`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 postApiSecurityKeysRegisterOptions<TData = unknown>(addSecurityKeyRequest: AddSecurityKeyRequest, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiSecurityKeysRegisterOptions<TData = unknown>(addSecurityKeyRequest: AddSecurityKeyRequest, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiSecurityKeysRegisterOptions<TData = unknown>(addSecurityKeyRequest: AddSecurityKeyRequest, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiSecurityKeysRegisterOptions<TData = unknown>(
    addSecurityKeyRequest: AddSecurityKeyRequest, options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/SecurityKeys/register/options`,
      addSecurityKeyRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/SecurityKeys/register/options`,
      addSecurityKeyRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/SecurityKeys/register/options`,
      addSecurityKeyRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 postApiSecurityKeysRegister<TData = unknown>(authenticatorAttestationRawResponse: AuthenticatorAttestationRawResponse,
    params?: PostApiSecurityKeysRegisterParams, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiSecurityKeysRegister<TData = unknown>(authenticatorAttestationRawResponse: AuthenticatorAttestationRawResponse,
    params?: PostApiSecurityKeysRegisterParams, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiSecurityKeysRegister<TData = unknown>(authenticatorAttestationRawResponse: AuthenticatorAttestationRawResponse,
    params?: PostApiSecurityKeysRegisterParams, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiSecurityKeysRegister<TData = unknown>(
    authenticatorAttestationRawResponse: AuthenticatorAttestationRawResponse,
    params?: PostApiSecurityKeysRegisterParams, options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    const filteredParams = filterParams({...params, ...options?.params}, new Set<string>([]));

    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/SecurityKeys/register`,
      authenticatorAttestationRawResponse,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
        params: filteredParams,}
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/SecurityKeys/register`,
      authenticatorAttestationRawResponse,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
        params: filteredParams,}
    );
    }

    return this.http.post<TData>(
      `/api/SecurityKeys/register`,
      authenticatorAttestationRawResponse,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
        params: filteredParams,}
    );
  }
 postApiSecurityKeysLoginOptions<TData = unknown>(jsonElement: JsonElement, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiSecurityKeysLoginOptions<TData = unknown>(jsonElement: JsonElement, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiSecurityKeysLoginOptions<TData = unknown>(jsonElement: JsonElement, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiSecurityKeysLoginOptions<TData = unknown>(
    jsonElement: JsonElement, options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/SecurityKeys/login/options`,
      jsonElement,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/SecurityKeys/login/options`,
      jsonElement,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/SecurityKeys/login/options`,
      jsonElement,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 postApiSecurityKeysLogin<TData = LoginResponse>(authenticatorAssertionRawResponse: AuthenticatorAssertionRawResponse,
    params?: PostApiSecurityKeysLoginParams, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiSecurityKeysLogin<TData = LoginResponse>(authenticatorAssertionRawResponse: AuthenticatorAssertionRawResponse,
    params?: PostApiSecurityKeysLoginParams, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiSecurityKeysLogin<TData = LoginResponse>(authenticatorAssertionRawResponse: AuthenticatorAssertionRawResponse,
    params?: PostApiSecurityKeysLoginParams, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiSecurityKeysLogin<TData = LoginResponse>(
    authenticatorAssertionRawResponse: AuthenticatorAssertionRawResponse,
    params?: PostApiSecurityKeysLoginParams, options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    const filteredParams = filterParams({...params, ...options?.params}, new Set<string>([]));

    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/SecurityKeys/login`,
      authenticatorAssertionRawResponse,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
        params: filteredParams,}
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/SecurityKeys/login`,
      authenticatorAssertionRawResponse,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
        params: filteredParams,}
    );
    }

    return this.http.post<TData>(
      `/api/SecurityKeys/login`,
      authenticatorAssertionRawResponse,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
        params: filteredParams,}
    );
  }
 deleteApiSecurityKeysId<TData = unknown>(id: number, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 deleteApiSecurityKeysId<TData = unknown>(id: number, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 deleteApiSecurityKeysId<TData = unknown>(id: number, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  deleteApiSecurityKeysId<TData = unknown>(
    id: number, options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.delete<TData>(
      `/api/SecurityKeys/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.delete<TData>(
      `/api/SecurityKeys/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.delete<TData>(
      `/api/SecurityKeys/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
}

