/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Backend | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient,
  HttpHeaders,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpParams
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  CreateShortUrlRequest,
  PutQsIdScreenshotBody,
  ShortUrlResponse
} from './generated.schemas';




interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
        | HttpParams
      | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: {includeHeaders?: string[]} | boolean;
  readonly timeout?: number;
}

type HttpClientBodyOptions = HttpClientOptions & {
  readonly observe?: 'body';
};

type HttpClientEventOptions = HttpClientOptions & {
  readonly observe: 'events';
};

type HttpClientResponseOptions = HttpClientOptions & {
  readonly observe: 'response';
};

type HttpClientObserveOptions = HttpClientOptions & {
  readonly observe?: 'body' | 'events' | 'response';
};







@Injectable({ providedIn: 'root' })
export class ShortUrlService {
  private readonly http = inject(HttpClient);
 getQsId<TData = unknown>(id: string, options?: HttpClientBodyOptions): Observable<TData>;
 getQsId<TData = unknown>(id: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getQsId<TData = unknown>(id: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getQsId<TData = unknown>(
    id: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/qs/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/qs/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/qs/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 postApiShortUrls<TData = ShortUrlResponse>(createShortUrlRequest: CreateShortUrlRequest, options?: HttpClientBodyOptions): Observable<TData>;
 postApiShortUrls<TData = ShortUrlResponse>(createShortUrlRequest: CreateShortUrlRequest, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiShortUrls<TData = ShortUrlResponse>(createShortUrlRequest: CreateShortUrlRequest, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiShortUrls<TData = ShortUrlResponse>(
    createShortUrlRequest: CreateShortUrlRequest, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/short-urls`,
      createShortUrlRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/short-urls`,
      createShortUrlRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/short-urls`,
      createShortUrlRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 getQsIdInfo<TData = unknown>(id: string, options?: HttpClientBodyOptions): Observable<TData>;
 getQsIdInfo<TData = unknown>(id: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getQsIdInfo<TData = unknown>(id: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getQsIdInfo<TData = unknown>(
    id: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/qs/${id}/info`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/qs/${id}/info`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/qs/${id}/info`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 putQsIdScreenshot<TData = unknown>(id: string,
    putQsIdScreenshotBody: PutQsIdScreenshotBody, options?: HttpClientBodyOptions): Observable<TData>;
 putQsIdScreenshot<TData = unknown>(id: string,
    putQsIdScreenshotBody: PutQsIdScreenshotBody, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 putQsIdScreenshot<TData = unknown>(id: string,
    putQsIdScreenshotBody: PutQsIdScreenshotBody, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  putQsIdScreenshot<TData = unknown>(
    id: string,
    putQsIdScreenshotBody: PutQsIdScreenshotBody, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {const formData = new FormData();
if(putQsIdScreenshotBody.file !== undefined) {
 formData.append(`file`, putQsIdScreenshotBody.file);
 }

    if (options?.observe === 'events') {
      return this.http.put<TData>(
      `/qs/${id}/screenshot`,
      formData,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.put<TData>(
      `/qs/${id}/screenshot`,
      formData,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.put<TData>(
      `/qs/${id}/screenshot`,
      formData,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 getQsIdLitematic<TData = unknown>(id: string, options?: HttpClientBodyOptions): Observable<TData>;
 getQsIdLitematic<TData = unknown>(id: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getQsIdLitematic<TData = unknown>(id: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getQsIdLitematic<TData = unknown>(
    id: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/qs/${id}/litematic`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/qs/${id}/litematic`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/qs/${id}/litematic`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
};

