/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Backend | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient,
  HttpHeaders,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpParams
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  ConfirmProfileUpdateRequest,
  EmailAvailableResponse,
  OwnProfileResponse,
  PublicProfileResponse,
  PutApiUsersMeCoverImageBody,
  PutApiUsersMeProfilePictureBody,
  RequestProfileUpdateRequest,
  SocialLinkRequest,
  SocialLinkResponse,
  UpdateProfileRequest,
  UsernameAvailableResponse
} from './generated.schemas';




interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
        | HttpParams
      | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: {includeHeaders?: string[]} | boolean;
  readonly timeout?: number;
}

type HttpClientBodyOptions = HttpClientOptions & {
  readonly observe?: 'body';
};

type HttpClientEventOptions = HttpClientOptions & {
  readonly observe: 'events';
};

type HttpClientResponseOptions = HttpClientOptions & {
  readonly observe: 'response';
};

type HttpClientObserveOptions = HttpClientOptions & {
  readonly observe?: 'body' | 'events' | 'response';
};







@Injectable({ providedIn: 'root' })
export class UsersService {
  private readonly http = inject(HttpClient);
 getApiUsersUsername<TData = PublicProfileResponse>(username: string, options?: HttpClientBodyOptions): Observable<TData>;
 getApiUsersUsername<TData = PublicProfileResponse>(username: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getApiUsersUsername<TData = PublicProfileResponse>(username: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getApiUsersUsername<TData = PublicProfileResponse>(
    username: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/Users/${username}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/Users/${username}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/Users/${username}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 getApiUsersMe<TData = OwnProfileResponse>( options?: HttpClientBodyOptions): Observable<TData>;
 getApiUsersMe<TData = OwnProfileResponse>( options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getApiUsersMe<TData = OwnProfileResponse>( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getApiUsersMe<TData = OwnProfileResponse>(
     options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/Users/me`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/Users/me`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/Users/me`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 postApiUsersMeRequestUpdate<TData = unknown>(requestProfileUpdateRequest: RequestProfileUpdateRequest, options?: HttpClientBodyOptions): Observable<TData>;
 postApiUsersMeRequestUpdate<TData = unknown>(requestProfileUpdateRequest: RequestProfileUpdateRequest, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiUsersMeRequestUpdate<TData = unknown>(requestProfileUpdateRequest: RequestProfileUpdateRequest, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiUsersMeRequestUpdate<TData = unknown>(
    requestProfileUpdateRequest: RequestProfileUpdateRequest, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/Users/me/request-update`,
      requestProfileUpdateRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/Users/me/request-update`,
      requestProfileUpdateRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/Users/me/request-update`,
      requestProfileUpdateRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 postApiUsersMeConfirmUpdate<TData = OwnProfileResponse>(confirmProfileUpdateRequest: ConfirmProfileUpdateRequest, options?: HttpClientBodyOptions): Observable<TData>;
 postApiUsersMeConfirmUpdate<TData = OwnProfileResponse>(confirmProfileUpdateRequest: ConfirmProfileUpdateRequest, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiUsersMeConfirmUpdate<TData = OwnProfileResponse>(confirmProfileUpdateRequest: ConfirmProfileUpdateRequest, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiUsersMeConfirmUpdate<TData = OwnProfileResponse>(
    confirmProfileUpdateRequest: ConfirmProfileUpdateRequest, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/Users/me/confirm-update`,
      confirmProfileUpdateRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/Users/me/confirm-update`,
      confirmProfileUpdateRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/Users/me/confirm-update`,
      confirmProfileUpdateRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 getApiUsersCheckUsernameUsername<TData = UsernameAvailableResponse>(username: string, options?: HttpClientBodyOptions): Observable<TData>;
 getApiUsersCheckUsernameUsername<TData = UsernameAvailableResponse>(username: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getApiUsersCheckUsernameUsername<TData = UsernameAvailableResponse>(username: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getApiUsersCheckUsernameUsername<TData = UsernameAvailableResponse>(
    username: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/Users/check-username/${username}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/Users/check-username/${username}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/Users/check-username/${username}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 getApiUsersCheckEmailEmail<TData = EmailAvailableResponse>(email: string, options?: HttpClientBodyOptions): Observable<TData>;
 getApiUsersCheckEmailEmail<TData = EmailAvailableResponse>(email: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getApiUsersCheckEmailEmail<TData = EmailAvailableResponse>(email: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getApiUsersCheckEmailEmail<TData = EmailAvailableResponse>(
    email: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/Users/check-email/${email}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/Users/check-email/${email}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/Users/check-email/${email}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 putApiUsersMeProfile<TData = OwnProfileResponse>(updateProfileRequest: UpdateProfileRequest, options?: HttpClientBodyOptions): Observable<TData>;
 putApiUsersMeProfile<TData = OwnProfileResponse>(updateProfileRequest: UpdateProfileRequest, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 putApiUsersMeProfile<TData = OwnProfileResponse>(updateProfileRequest: UpdateProfileRequest, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  putApiUsersMeProfile<TData = OwnProfileResponse>(
    updateProfileRequest: UpdateProfileRequest, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.put<TData>(
      `/api/Users/me/profile`,
      updateProfileRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.put<TData>(
      `/api/Users/me/profile`,
      updateProfileRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.put<TData>(
      `/api/Users/me/profile`,
      updateProfileRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 putApiUsersMeProfilePicture<TData = OwnProfileResponse>(putApiUsersMeProfilePictureBody: PutApiUsersMeProfilePictureBody, options?: HttpClientBodyOptions): Observable<TData>;
 putApiUsersMeProfilePicture<TData = OwnProfileResponse>(putApiUsersMeProfilePictureBody: PutApiUsersMeProfilePictureBody, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 putApiUsersMeProfilePicture<TData = OwnProfileResponse>(putApiUsersMeProfilePictureBody: PutApiUsersMeProfilePictureBody, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  putApiUsersMeProfilePicture<TData = OwnProfileResponse>(
    putApiUsersMeProfilePictureBody: PutApiUsersMeProfilePictureBody, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {const formData = new FormData();
if(putApiUsersMeProfilePictureBody.file !== undefined) {
 formData.append(`file`, putApiUsersMeProfilePictureBody.file);
 }

    if (options?.observe === 'events') {
      return this.http.put<TData>(
      `/api/Users/me/profile-picture`,
      formData,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.put<TData>(
      `/api/Users/me/profile-picture`,
      formData,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.put<TData>(
      `/api/Users/me/profile-picture`,
      formData,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 deleteApiUsersMeProfilePicture<TData = OwnProfileResponse>( options?: HttpClientBodyOptions): Observable<TData>;
 deleteApiUsersMeProfilePicture<TData = OwnProfileResponse>( options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 deleteApiUsersMeProfilePicture<TData = OwnProfileResponse>( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  deleteApiUsersMeProfilePicture<TData = OwnProfileResponse>(
     options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.delete<TData>(
      `/api/Users/me/profile-picture`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.delete<TData>(
      `/api/Users/me/profile-picture`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.delete<TData>(
      `/api/Users/me/profile-picture`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 putApiUsersMeCoverImage<TData = OwnProfileResponse>(putApiUsersMeCoverImageBody: PutApiUsersMeCoverImageBody, options?: HttpClientBodyOptions): Observable<TData>;
 putApiUsersMeCoverImage<TData = OwnProfileResponse>(putApiUsersMeCoverImageBody: PutApiUsersMeCoverImageBody, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 putApiUsersMeCoverImage<TData = OwnProfileResponse>(putApiUsersMeCoverImageBody: PutApiUsersMeCoverImageBody, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  putApiUsersMeCoverImage<TData = OwnProfileResponse>(
    putApiUsersMeCoverImageBody: PutApiUsersMeCoverImageBody, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {const formData = new FormData();
if(putApiUsersMeCoverImageBody.file !== undefined) {
 formData.append(`file`, putApiUsersMeCoverImageBody.file);
 }

    if (options?.observe === 'events') {
      return this.http.put<TData>(
      `/api/Users/me/cover-image`,
      formData,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.put<TData>(
      `/api/Users/me/cover-image`,
      formData,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.put<TData>(
      `/api/Users/me/cover-image`,
      formData,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 deleteApiUsersMeCoverImage<TData = OwnProfileResponse>( options?: HttpClientBodyOptions): Observable<TData>;
 deleteApiUsersMeCoverImage<TData = OwnProfileResponse>( options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 deleteApiUsersMeCoverImage<TData = OwnProfileResponse>( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  deleteApiUsersMeCoverImage<TData = OwnProfileResponse>(
     options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.delete<TData>(
      `/api/Users/me/cover-image`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.delete<TData>(
      `/api/Users/me/cover-image`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.delete<TData>(
      `/api/Users/me/cover-image`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 putApiUsersMeSocialLinks<TData = SocialLinkResponse[]>(socialLinkRequest: SocialLinkRequest[], options?: HttpClientBodyOptions): Observable<TData>;
 putApiUsersMeSocialLinks<TData = SocialLinkResponse[]>(socialLinkRequest: SocialLinkRequest[], options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 putApiUsersMeSocialLinks<TData = SocialLinkResponse[]>(socialLinkRequest: SocialLinkRequest[], options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  putApiUsersMeSocialLinks<TData = SocialLinkResponse[]>(
    socialLinkRequest: SocialLinkRequest[], options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.put<TData>(
      `/api/Users/me/social-links`,
      socialLinkRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.put<TData>(
      `/api/Users/me/social-links`,
      socialLinkRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.put<TData>(
      `/api/Users/me/social-links`,
      socialLinkRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
};

