/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Backend | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient,
  HttpHeaders
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpParams,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  GetApiUserBrowseParams,
  GetApiUserBrowseSearchParams,
  UserLikeResponse,
  UserListResponse,
  UserProfileResponse
} from './generated.schemas';




interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
        | HttpParams
      | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: {includeHeaders?: string[]} | boolean;
}

function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: Set<string> = new Set(),
): Record<string, string | number | boolean | Array<string | number | boolean>> {
  const filteredParams: Record<string, string | number | boolean | null | Array<string | number | boolean>> = {};
  for (const [key, value] of Object.entries(params)) {
    if (Array.isArray(value)) {
      const filtered = value.filter(
        (item) =>
          item != null &&
          (typeof item === 'string' ||
            typeof item === 'number' ||
            typeof item === 'boolean'),
      ) as Array<string | number | boolean>;
      if (filtered.length) {
        filteredParams[key] = filtered;
      }
    } else if (value === null && requiredNullableKeys.has(key)) {
      filteredParams[key] = value;
    } else if (
      value != null &&
      (typeof value === 'string' ||
        typeof value === 'number' ||
        typeof value === 'boolean')
    ) {
      filteredParams[key] = value as string | number | boolean;
    }
  }
  return filteredParams as Record<string, string | number | boolean | Array<string | number | boolean>>;
}



@Injectable({ providedIn: 'root' })
export class UserBrowseService {
  private readonly http = inject(HttpClient);
 getApiUserBrowse<TData = UserListResponse>(params?: GetApiUserBrowseParams, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 getApiUserBrowse<TData = UserListResponse>(params?: GetApiUserBrowseParams, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 getApiUserBrowse<TData = UserListResponse>(params?: GetApiUserBrowseParams, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  getApiUserBrowse<TData = UserListResponse>(
    params?: GetApiUserBrowseParams, options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    const filteredParams = filterParams({...params, ...options?.params}, new Set<string>([]));

    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/UserBrowse`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
        params: filteredParams,}
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/UserBrowse`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
        params: filteredParams,}
    );
    }

    return this.http.get<TData>(
      `/api/UserBrowse`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
        params: filteredParams,}
    );
  }
 getApiUserBrowseUsernameProfile<TData = UserProfileResponse>(username: string, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 getApiUserBrowseUsernameProfile<TData = UserProfileResponse>(username: string, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 getApiUserBrowseUsernameProfile<TData = UserProfileResponse>(username: string, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  getApiUserBrowseUsernameProfile<TData = UserProfileResponse>(
    username: string, options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/UserBrowse/${username}/profile`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/UserBrowse/${username}/profile`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/UserBrowse/${username}/profile`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 postApiUserBrowseUserIdLike<TData = UserLikeResponse>(userId: string, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiUserBrowseUserIdLike<TData = UserLikeResponse>(userId: string, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiUserBrowseUserIdLike<TData = UserLikeResponse>(userId: string, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiUserBrowseUserIdLike<TData = UserLikeResponse>(
    userId: string, options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/UserBrowse/${userId}/like`,undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/UserBrowse/${userId}/like`,undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/UserBrowse/${userId}/like`,undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 getApiUserBrowseSearch<TData = string[]>(params?: GetApiUserBrowseSearchParams, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 getApiUserBrowseSearch<TData = string[]>(params?: GetApiUserBrowseSearchParams, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 getApiUserBrowseSearch<TData = string[]>(params?: GetApiUserBrowseSearchParams, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  getApiUserBrowseSearch<TData = string[]>(
    params?: GetApiUserBrowseSearchParams, options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    const filteredParams = filterParams({...params, ...options?.params}, new Set<string>([]));

    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/UserBrowse/search`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
        params: filteredParams,}
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/UserBrowse/search`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
        params: filteredParams,}
    );
    }

    return this.http.get<TData>(
      `/api/UserBrowse/search`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
        params: filteredParams,}
    );
  }
}

